;;; emacs-agents-actions-tests.el --- Contextual menu tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(unless (boundp 'emacs-agents-test-root)
  (load (expand-file-name "emacs-agents-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))
(require 'emacs-agents-actions)
(require 'emacs-agents-board)

(ert-deftest emacs-agents-actions-ui-open-close-is-read-only ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Menu target" repo "test"))
           (before (emacs-agents--query "SELECT * FROM sessions")))
      (emacs-agents)
      (when (bound-and-true-p evil-mode) (evil-motion-state))
      (should (eq (key-binding (kbd "?")) #'emacs-agents-actions))
      (let ((layout (current-window-configuration)))
        (cl-letf (((symbol-function 'emacs-agents-start) (lambda (&rest _) (ert-fail "Menu launched an agent"))))
          (call-interactively (key-binding (kbd "?")))
          (when (bound-and-true-p evil-mode) (evil-motion-state))
          (should (equal id emacs-agents-actions--id))
          (should (string-match-p "No tracked process" (buffer-string)))
          (should buffer-read-only)
          (should-not emacs-agents--managed-id)
          (should (eq (key-binding (kbd "q")) #'emacs-agents-actions-close))
          (emacs-agents--maybe-read-current)
          (call-interactively (key-binding (kbd "q"))))
        (should (compare-window-configurations layout (current-window-configuration))))
      (should (equal before (emacs-agents--query "SELECT * FROM sessions"))))))

(ert-deftest emacs-agents-actions-state-availability-and-revalidation ()
  (emacs-agents-test-with-store
    (let ((id (emacs-agents-create "State" repo "test")))
      (emacs-agents)
      (emacs-agents-actions)
      (let ((rows (emacs-agents-actions--entries (emacs-agents-actions--session))))
        (should-not (nth 3 (assoc "o" rows)))
        (should (nth 3 (assoc "x" rows)))
        (should (nth 3 (assoc "r" rows))))
      (emacs-agents--exec "UPDATE sessions SET archived=1 WHERE id=?" id)
      (cl-letf (((symbol-function 'emacs-agents-open) (lambda (&rest _) (ert-fail "Archived agent opened"))))
        (should-error (emacs-agents-actions--run "o") :type 'user-error))
      (should (string-match-p "Restore this archived" (buffer-string)))
      (should-not (nth 3 (assoc "s" (emacs-agents-actions--entries (emacs-agents-actions--session)))))
      (emacs-agents-actions--run "s")
      (should-not (emacs-agents-archived-p (emacs-agents-session id)))
      (should (zerop (hash-table-count emacs-agents--running)))
      (emacs-agents-actions)
      (let ((before (emacs-agents--query "SELECT * FROM sessions")))
        (should-error (emacs-agents-actions--run "u") :type 'user-error)
        (should (equal before (emacs-agents--query "SELECT * FROM sessions"))))
      (emacs-agents--exec "DELETE FROM sessions WHERE id=?" id)
      (should-error (emacs-agents-actions--run "i") :type 'user-error)
      (should (string-match-p "Agent record deleted" (buffer-string))))))

(ert-deftest emacs-agents-actions-pin-target-and-retain-delete-confirmation ()
  (emacs-agents-test-with-store
    (let ((first (emacs-agents-create "First" repo "test"))
          (second (emacs-agents-create "Second" repo "test")))
      (emacs-agents)
      (emacs-agents-actions)
      (with-current-buffer "*Agent Overview*" (goto-char (emacs-agents--sidebar-position second)))
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "Renamed first")))
        (emacs-agents-actions--run "R"))
      (should (equal "Renamed first" (emacs-agents-session-name (emacs-agents-session first))))
      (should (equal "Second" (emacs-agents-session-name (emacs-agents-session second))))
      (emacs-agents-actions)
      (let ((before (emacs-agents--query "SELECT * FROM sessions")) prompted)
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (prompt) (setq prompted prompt) nil)))
          (should-error (emacs-agents-actions--run "d") :type 'user-error))
        (should (string-match-p "Renamed first" prompted))
        (should (equal before (emacs-agents--query "SELECT * FROM sessions")))))))

(ert-deftest emacs-agents-actions-running-archive-cancellation-does-not-stop ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Running" repo "test"))
           (run (emacs-agents--begin-run id))
           (buffer (generate-new-buffer "*Menu running fixture*"))
           (transport (emacs-agents--transport-create :buffer buffer)))
      (unwind-protect
          (progn
            (puthash id (cons run transport) emacs-agents--running)
            (emacs-agents)
            (emacs-agents-actions)
            (let ((rows (emacs-agents-actions--entries (emacs-agents-actions--session))))
              (should-not (nth 3 (assoc "o" rows)))
              (should-not (nth 3 (assoc "x" rows)))
              (should (nth 3 (assoc "W" rows)))
              (should (equal "Stop and archive…" (nth 1 (assoc "a" rows)))))
            (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) nil))
                      ((symbol-function 'emacs-agents-stop) (lambda (&rest _) (ert-fail "Cancelled archive stopped agent"))))
              (should-error (emacs-agents-actions--run "a") :type 'user-error))
            (should (gethash id emacs-agents--running))
            (should-not (emacs-agents-archived-p (emacs-agents-session id))))
        (remhash id emacs-agents--running)
        (kill-buffer buffer)))))

(ert-deftest emacs-agents-actions-ui-key-dispatch-and-board-return ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Board card" repo "test"))
           (conversation (generate-new-buffer "*Menu conversation*")))
      (unwind-protect
          (progn
            (with-current-buffer conversation
              (setq-local emacs-agents--managed-id id)
              (insert "Unsent draft"))
            (emacs-agents-board)
            (when (bound-and-true-p evil-mode) (evil-motion-state))
            (call-interactively (key-binding (kbd "?")))
            (when (bound-and-true-p evil-mode) (evil-motion-state))
            (cl-letf (((symbol-function 'emacs-agents-start) (lambda (selected) (should (equal id selected)) conversation)))
              (execute-kbd-macro (kbd "o")))
            (should (eq (window-buffer (selected-window)) conversation))
            (should-not (get-buffer-window "*Agent Actions*"))
            (emacs-agents-close-view)
            (should (get-buffer-window "*Agent Board*"))
            (with-current-buffer "*Agent Board*" (should (equal id emacs-agents-board--selection)))
            (should (equal "Unsent draft" (with-current-buffer conversation (buffer-string)))))
        (with-current-buffer conversation (set-buffer-modified-p nil))
        (kill-buffer conversation)))))

(ert-deftest emacs-agents-actions-empty-and-folder-context ()
  (emacs-agents-test-with-store
    (let ((origin (current-buffer)))
      (emacs-agents-actions)
      (should-not (file-exists-p emacs-agents-directory))
      (should (nth 3 (assoc "o" (emacs-agents-actions--entries nil))))
      (should-not (nth 3 (assoc "n" (emacs-agents-actions--entries nil))))
      (emacs-agents-actions-close)
      (should (eq origin (current-buffer))))
    (emacs-agents-folder-create "Work")
    (emacs-agents)
    (emacs-agents-actions)
    (should (equal "Work" emacs-agents-actions--folder))
    (should-not (nth 3 (assoc "TAB" (emacs-agents-actions--entries nil))))
    (emacs-agents-actions--run "TAB")
    (should (member "Work" emacs-agents--collapsed))))

;;; emacs-agents-actions-tests.el ends here
