;;; emacs-agents-archive-tests.el --- Record lifecycle tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(unless (boundp 'emacs-agents-test-root)
  (load (expand-file-name "emacs-agents-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))

(ert-deftest emacs-agents-archive-persists-and-restores-without-starting ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Finished work" repo "test" "Work/Project"))
           (run (emacs-agents--begin-run id)))
      (emacs-agents--observe id run "stopped" "unknown" "saved-history")
      (emacs-agents--exec "UPDATE sessions SET unread=1,model='known-model' WHERE id=?" id)
      (emacs-agents)
      (emacs-agents-archive id)
      (should-not (emacs-agents-sessions))
      (should (= 1 (length (emacs-agents-sessions 'all))))
      (should (equal emacs-agents--summary " Agents: 0"))
      (should-not (with-current-buffer "*Agent Overview*" (string-match-p "Finished work" (buffer-string))))
      (should-error (emacs-agents-start id) :type 'user-error)
      (emacs-agents-store-close)
      (let ((session (car (emacs-agents-sessions 'archived))))
        (should (emacs-agents-archived-p session))
        (should (equal (emacs-agents-session-conversation session) "saved-history"))
        (should (equal (emacs-agents-session-folder session) "Work/Project"))
        (should (equal (emacs-agents-session-model session) "known-model"))
        (should (emacs-agents-unread-p session)))
      (emacs-agents-archived)
      (goto-char (point-min))
      (when (bound-and-true-p evil-mode) (evil-motion-state))
      (should (eq (key-binding (kbd "RET")) #'emacs-agents-restore))
      (should (equal (tabulated-list-get-id) id))
      (cl-letf (((symbol-function 'emacs-agents-backend-start)
                 (lambda (&rest _) (ert-fail "Restore must not launch a backend"))))
        (call-interactively (key-binding (kbd "RET"))))
      (should-not (emacs-agents-sessions 'archived))
      (should (= 1 (length (emacs-agents-sessions))))
      (should (equal (emacs-agents-session-run (emacs-agents-session id)) run))
      (should (equal (emacs-agents-session-status (emacs-agents-session id)) "stopped")))))

(ert-deftest emacs-agents-v2-migration-preserves-live-observations ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Existing" repo "test"))
           (run (emacs-agents--begin-run id)))
      (emacs-agents--observe id run "live" "working" "saved-history")
      (emacs-agents--exec "ALTER TABLE sessions DROP COLUMN archived")
      (emacs-agents--exec "PRAGMA user_version=2")
      (emacs-agents-store-migrate)
      (emacs-agents-store-migrate)
      (let ((session (emacs-agents-session id)))
        (should (equal (emacs-agents-session-status session) "live"))
        (should (equal (emacs-agents-session-conversation session) "saved-history"))
        (should-not (emacs-agents-archived-p session))))))

(ert-deftest emacs-agents-delete-is-atomic-preserves-files-and-ignores-late-events ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Delete me" repo "test"))
           (run (emacs-agents--begin-run id))
           (file (expand-file-name "uncommitted-draft" repo))
           (history (expand-file-name "saved-conversation.jsonl" temporary))
           (buffer (generate-new-buffer "*Retained agent text*")))
      (unwind-protect
          (progn
            (write-region "local draft" nil file nil 'silent)
            (write-region "saved conversation" nil history nil 'silent)
            (emacs-agents--observe id run "stopped" "unknown" "saved-history")
            (with-current-buffer buffer
              (insert "Agent text retained")
              (setq-local emacs-agents--managed-id id)
              (emacs-agents-conversation-mode 1))
            (let ((execute (symbol-function 'emacs-agents--exec)))
              (cl-letf (((symbol-function 'emacs-agents--exec)
                         (lambda (sql &rest values)
                           (if (equal sql "DELETE FROM sessions WHERE id=?")
                               (error "Simulated deletion failure")
                             (apply execute sql values)))))
                (should-error (emacs-agents-delete id))))
            (should (emacs-agents-session id))
            (should (emacs-agents--query "SELECT id FROM runs WHERE session=?" id))
            (emacs-agents-delete id)
            (should-not (emacs-agents-session id t))
            (should-not (emacs-agents--query "SELECT id FROM runs WHERE session=?" id))
            (should-not (emacs-agents--observe id run "live" "working" "saved-history"))
            (should (file-readable-p file))
            (should (file-readable-p history))
            (should (equal (emacs-agents--git repo "branch" "--show-current") "main"))
            (with-current-buffer buffer
              (should (equal (buffer-string) "Agent text retained"))
              (should-not emacs-agents--managed-id)
              (should-not emacs-agents-conversation-mode)))
        (when (buffer-live-p buffer) (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))))))

(ert-deftest emacs-agents-removal-cancellation-does-not-stop-or-change-records ()
  (emacs-agents-test-with-store
    (let ((id (emacs-agents-create "Running" repo "test")))
      (puthash id '(fake-run . fake-transport) emacs-agents--running)
      (unwind-protect
          (cl-letf (((symbol-function 'emacs-agents--read-id) (lambda () id))
                    ((symbol-function 'y-or-n-p) (lambda (&rest _) nil))
                    ((symbol-function 'yes-or-no-p) (lambda (&rest _) nil))
                    ((symbol-function 'emacs-agents-stop) (lambda (&rest _) (ert-fail "Must not stop on cancellation"))))
            (should-error (call-interactively #'emacs-agents-archive) :type 'user-error)
            (should-error (call-interactively #'emacs-agents-delete) :type 'user-error)
            (should-error (emacs-agents-archive id) :type 'user-error)
            (should-error (emacs-agents-delete id) :type 'user-error)
            (should-not (emacs-agents-archived-p (emacs-agents-session id)))
            (should (gethash id emacs-agents--running)))
        (remhash id emacs-agents--running)))))
