;;; emacs-agents-recovery-tests.el --- Worktree recovery tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(unless (boundp 'emacs-agents-test-root)
  (load (expand-file-name "emacs-agents-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))
(require 'emacs-agents-recovery)

(ert-deftest emacs-agents-recovery-accept-branch-preserves-identity-and-files ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Retain identity" repo "account-profile" "Work/Project"))
           (run (emacs-agents--begin-run id))
           (file (expand-file-name "draft" repo)))
      (emacs-agents--observe id run "failed" "unknown" "original-conversation" "Previous failure")
      (emacs-agents--exec "UPDATE sessions SET unread=1,model='known-model' WHERE id=?" id)
      (write-region "unsaved work" nil file nil 'silent)
      (emacs-agents--git repo "checkout" "-b" "new-branch")
      (let* ((before (emacs-agents-session id))
             (expected (copy-emacs-agents-session before))
             (runs (emacs-agents--query "SELECT * FROM runs"))
             (head (emacs-agents--git repo "rev-parse" "HEAD"))
             (dirty (emacs-agents--git repo "status" "--porcelain")))
        (setf (emacs-agents-session-branch expected) "new-branch")
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (prompt)
                     (should (string-match-p "Recorded:.*\\[main\\]" prompt))
                     (should (string-match-p "Proposed:.*\\[new-branch\\]" prompt))
                     (should (equal before (emacs-agents-session id))) t))
                  ((symbol-function 'emacs-agents-backend-start) (lambda (&rest _) (ert-fail "Recovery launched an agent"))))
          (emacs-agents-rebind-worktree id repo))
        (should (equal expected (emacs-agents-session id)))
        (should (equal runs (emacs-agents--query "SELECT * FROM runs")))
        (should (equal head (emacs-agents--git repo "rev-parse" "HEAD")))
        (should (equal dirty (emacs-agents--git repo "status" "--porcelain")))
        (emacs-agents-store-close)
        (should (equal expected (emacs-agents-session id)))))))

(ert-deftest emacs-agents-recovery-relocated-linked-worktree-and-shell-draft ()
  (emacs-agents-test-with-store
    (let* ((old (expand-file-name "old-checkout" temporary))
           (new (expand-file-name "moved-checkout" temporary))
           (id (emacs-agents-create-worktree "Moved" repo "test" "agent/work" old))
           (shell (emacs-agents-eshell id)))
      (insert "echo unsent draft")
      (let ((draft (buffer-string)) (shell-directory default-directory))
        (emacs-agents--git repo "worktree" "move" old new)
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
          (emacs-agents-rebind-worktree id new))
        (should-not (file-exists-p old))
        (should (equal (emacs-agents-session-directory (emacs-agents-session id))
                       (file-name-as-directory (file-truename new))))
        (should (equal (emacs-agents-session-project (emacs-agents-session id)) "worktree"))
        (with-current-buffer shell
          (should (equal draft (buffer-string)))
          (should (equal shell-directory default-directory))
          (should-not emacs-agents--shell-id))
        (unwind-protect
            (let ((new-shell (emacs-agents-eshell id)))
              (should-not (eq shell new-shell))
              (should (file-equal-p default-directory new))
              (set-buffer-modified-p nil)
              (kill-buffer new-shell))
          (with-current-buffer shell (set-buffer-modified-p nil))
          (kill-buffer shell))))))

(ert-deftest emacs-agents-recovery-cancel-cold-registry-and-invalid-target ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Cancel" repo "test"))
           (other (emacs-agents-create "Other live observation" repo "test"))
           (run (emacs-agents--begin-run other)))
      (emacs-agents--observe other run "live" "working" "other-conversation")
      (emacs-agents--git repo "checkout" "-b" "changed")
      (let ((sessions (emacs-agents--query "SELECT * FROM sessions"))
            (runs (emacs-agents--query "SELECT * FROM runs")))
        (emacs-agents-store-close)
        (cl-letf (((symbol-function 'emacs-agents-store-open) (lambda () (ert-fail "Cancelled recovery opened registry")))
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
          (should-error (emacs-agents-rebind-worktree id repo) :type 'user-error)
          (should-error (emacs-agents-rebind-worktree id (expand-file-name "missing" temporary)) :type 'user-error)
          (should-error (emacs-agents-rebind-worktree id temporary) :type 'user-error)
          (should-error (emacs-agents-rebind-worktree id "/ssh:fixture:/repo/") :type 'user-error)
          (cl-letf (((symbol-function 'read-directory-name) (lambda (&rest _) (signal 'quit nil))))
            (should (eq (condition-case nil (emacs-agents-rebind-worktree id) (quit 'cancelled)) 'cancelled))))
        (should-not emacs-agents--db)
        (let ((db (sqlite-open (expand-file-name "sessions.sqlite" emacs-agents-directory))))
          (unwind-protect
              (progn (should (equal sessions (sqlite-select db "SELECT * FROM sessions")))
                     (should (equal runs (sqlite-select db "SELECT * FROM runs"))))
            (sqlite-close db)))))))

(ert-deftest emacs-agents-recovery-rejects-starting-tracked-and-lingering-process ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Busy" repo "test"))
           (run (emacs-agents--begin-run id))
           (buffer (generate-new-buffer "*Recovery process*"))
           (process (make-pipe-process :name "recovery-fixture" :buffer buffer :noquery t)))
      (unwind-protect
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) (ert-fail "Running agents must be rejected before confirmation"))))
            (should-error (emacs-agents-rebind-worktree id repo) :type 'user-error)
            (emacs-agents--observe id run "stopped" "unknown" "saved-id")
            (puthash id (cons run (emacs-agents--transport-create :buffer buffer)) emacs-agents--running)
            (should-error (emacs-agents-rebind-worktree id repo) :type 'user-error)
            (remhash id emacs-agents--running)
            (with-current-buffer buffer
              (setq emacs-agents--managed-id id emacs-agents--backend-kind 'eat))
            (should-error (emacs-agents-rebind-worktree id repo) :type 'user-error)
            (with-current-buffer buffer
              (setq emacs-agents--backend-kind 'agent-shell)
              (setq-local agent-shell--state (list (cons :client (list (cons :process process))))))
            (should-error (emacs-agents-rebind-worktree id repo) :type 'user-error)
            (should (process-live-p process)))
        (remhash id emacs-agents--running)
        (delete-process process)
        (kill-buffer buffer)))))

(ert-deftest emacs-agents-recovery-revalidates-confirmed-state ()
  (emacs-agents-test-with-store
    (let ((id (emacs-agents-create "Race" repo "test")))
      (emacs-agents--git repo "checkout" "-b" "proposed")
      (cl-letf (((symbol-function 'yes-or-no-p)
                 (lambda (&rest _) (emacs-agents--git repo "checkout" "-b" "changed-again") t)))
        (should-error (emacs-agents-rebind-worktree id repo) :type 'user-error))
      (should (equal (emacs-agents-session-branch (emacs-agents-session id)) "main"))
      (cl-letf (((symbol-function 'yes-or-no-p)
                 (lambda (&rest _) (emacs-agents-rename id "Renamed during prompt") t)))
        (should-error (emacs-agents-rebind-worktree id repo) :type 'user-error))
      (should (equal (emacs-agents-session-branch (emacs-agents-session id)) "main"))
      (cl-letf (((symbol-function 'yes-or-no-p)
                 (lambda (&rest _) (emacs-agents--begin-run id) t)))
        (should-error (emacs-agents-rebind-worktree id repo) :type 'user-error))
      (should (equal (emacs-agents-session-branch (emacs-agents-session id)) "main")))))

(ert-deftest emacs-agents-recovery-write-failure-rolls-back ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Write failure" repo "test"))
           (before (emacs-agents-session id))
           (execute (symbol-function 'emacs-agents--exec)))
      (emacs-agents--git repo "checkout" "-b" "proposed")
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                ((symbol-function 'emacs-agents--exec)
                 (lambda (sql &rest values)
                   (prog1 (apply execute sql values)
                     (when (string-prefix-p "UPDATE sessions SET directory=" sql)
                       (error "Fixture write failure"))))))
        (should-error (emacs-agents-rebind-worktree id repo)))
      (should (equal before (emacs-agents-session id))))))

(ert-deftest emacs-agents-recovery-ui-default-branch-and-noop ()
  (emacs-agents-test-with-store
    (let ((id (emacs-agents-create "Inspect and recover" repo "test")))
      (emacs-agents--git repo "checkout" "-b" "accepted")
      (emacs-agents-diagnostics id)
      (when (bound-and-true-p evil-mode) (evil-normal-state))
      (should (eq (key-binding (kbd "W")) #'emacs-agents-rebind-worktree))
      (cl-letf (((symbol-function 'read-directory-name)
                 (lambda (_ directory &rest _) (should (file-equal-p directory repo)) directory))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (call-interactively (key-binding (kbd "W"))))
      (should (string-match-p "Recorded branch: accepted" (buffer-string)))
      (should-not (string-match-p "Worktree mismatch" (buffer-string)))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) (ert-fail "No-op prompted")))
                ((symbol-function 'emacs-agents--exec) (lambda (&rest _) (ert-fail "No-op wrote registry"))))
        (emacs-agents-rebind-worktree id repo)))))


(ert-deftest emacs-agents-retry-cancel-and-invalid-preconditions-do-not-write ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Retry" repo "original"))
           (empty (emacs-agents-create "Never launched" repo "original"))
           (run (emacs-agents--begin-run id))
           (configs '(((:identifier . original) (:interface . eat) (:command . ("python3"))))))
      (emacs-agents--observe id run "failed" "unknown" "original-id" "Authentication failed")
      (let ((sessions (emacs-agents--query "SELECT * FROM sessions"))
            (runs (emacs-agents--query "SELECT * FROM runs")))
        (emacs-agents-store-close)
        (cl-letf (((symbol-function 'emacs-agents-backend-configs) (lambda () configs))
                  ((symbol-function 'emacs-agents-open) (lambda (&rest _) (ert-fail "Unexpected start")))
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
          (should-error (emacs-agents-retry id) :type 'user-error)
          (should-error (emacs-agents-retry empty) :type 'user-error)
          (setq configs '(((:identifier . similar-name) (:interface . eat))))
          (should-error (emacs-agents-retry id) :type 'user-error)
          (should-not emacs-agents--db)
          (let ((db (sqlite-open (expand-file-name "sessions.sqlite" emacs-agents-directory))))
            (unwind-protect
                (progn (should (equal sessions (sqlite-select db "SELECT * FROM sessions")))
                       (should (equal runs (sqlite-select db "SELECT * FROM runs"))))
              (sqlite-close db))))))))

(ert-deftest emacs-agents-retry-revalidates-profile-and-record ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Retry" repo "original"))
           (run (emacs-agents--begin-run id))
           (configs '(((:identifier . original) (:interface . eat) (:command . ("python3"))))))
      (emacs-agents--observe id run "stopped" "unknown" "original-id")
      (cl-letf (((symbol-function 'emacs-agents-backend-configs) (lambda () configs))
                ((symbol-function 'emacs-agents-open) (lambda (&rest _) (ert-fail "Changed state launched"))))
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (&rest _) (setq configs '(((:identifier . original) (:interface . vterm)))) t)))
          (should-error (emacs-agents-retry id) :type 'user-error))
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (&rest _) (emacs-agents-rename id "Changed") t)))
          (should-error (emacs-agents-retry id) :type 'user-error))
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (&rest _) (emacs-agents--begin-run id) t)))
          (should-error (emacs-agents-retry id) :type 'user-error)))
      (should (equal "original-id" (emacs-agents-session-conversation (emacs-agents-session id)))))))

(ert-deftest emacs-agents-retry-ui-and-guidance-do-not-expose-payloads ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-create "Retry" repo "original"))
           (run (emacs-agents--begin-run id))
           (config '((:identifier . original) (:interface . eat) (:command . ("python3" "SECRET-ARGV")))))
      (emacs-agents--observe id run "stopped" "unknown" "original-id")
      (cl-letf (((symbol-function 'emacs-agents-backend-configs) (lambda () (list config))))
        (dolist (case '(("Authentication failed SECRET-ERROR" authentication "Sign in again")
                        ("Unsupported resume SECRET-ERROR" unsupported "Repeated retries cannot")
                        ("Cannot find conversation SECRET-ERROR" history "backup")
                        ("Resume failed: inspect history SECRET-ERROR" resume "backend may have rejected")
                        ("Exited before confirming SECRET-ERROR" unconfirmed "does not identify")))
          (emacs-agents--exec "UPDATE sessions SET error=? WHERE id=?" (car case) id)
          (should (eq (emacs-agents-diagnostics--failure-kind (car case)) (nth 1 case)))
          (let ((report (emacs-agents-diagnostics--text (emacs-agents-diagnostics--collect id))))
            (should (string-match-p (nth 2 case) report))
            (should-not (string-match-p "SECRET-" report))))
        (emacs-agents-diagnostics id)
        (when (bound-and-true-p evil-mode) (evil-normal-state))
        (should (eq (key-binding (kbd "R")) #'emacs-agents-retry))
        (let (opened)
          (cl-letf (((symbol-function 'yes-or-no-p)
                     (lambda (prompt) (should (string-match-p "original-id" prompt)) t))
                    ((symbol-function 'emacs-agents-open) (lambda (selected) (setq opened selected))))
            (call-interactively (key-binding (kbd "R"))))
          (should (equal opened id)))))))

;;; emacs-agents-recovery-tests.el ends here
