;;; emacs-agents-attention-tests.el --- Attention navigation tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(unless (boundp 'emacs-agents-test-root)
  (load (expand-file-name "emacs-agents-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))
(require 'emacs-agents-attention)
(require 'emacs-agents-board)

(defun emacs-agents-attention-test-create (repo name state unread &optional folder)
  "Create a fixture in REPO named NAME with STATE, UNREAD and FOLDER."
  (let* ((id (emacs-agents-create name repo "test" folder))
         (run (emacs-agents--begin-run id)))
    (emacs-agents--observe id run (if (equal state "stopped") "stopped" "live") state "saved")
    (when unread (emacs-agents--exec "UPDATE sessions SET unread=1 WHERE id=?" id))
    id))

(ert-deftest emacs-agents-attention-priority-wrap-dedup-and-exclusions ()
  (emacs-agents-test-with-store
    (let* ((unread (emacs-agents-attention-test-create repo "Old unread" "input" t))
           (approval (emacs-agents-attention-test-create repo "Approval and unread" "approval" t))
           (waiting (emacs-agents-attention-test-create repo "Question" "waiting" nil))
           (stopped (emacs-agents-attention-test-create repo "Stopped unread" "stopped" t))
           (archived (emacs-agents-attention-test-create repo "Archived" "approval" t)))
      (emacs-agents-attention-test-create repo "Idle" "input" nil)
      (emacs-agents-attention-test-create repo "Busy" "working" nil)
      (emacs-agents-archive archived)
      (let* ((sessions (emacs-agents-sessions 'all))
             (queue (emacs-agents-attention--queue sessions 'all)))
        (should (equal (mapcar #'emacs-agents-session-id queue) (list approval waiting unread stopped)))
        (should (equal (mapcar #'emacs-agents-session-id (emacs-agents-attention--queue sessions 'waiting))
                       (list approval waiting)))
        (should (equal (mapcar #'emacs-agents-session-id (emacs-agents-attention--queue sessions 'unread))
                       (list unread approval stopped)))
        (dolist (previous '(nil t))
          (should (equal approval (emacs-agents-session-id (emacs-agents-attention--target queue nil previous)))))
        (should (equal approval (emacs-agents-session-id (emacs-agents-attention--target queue stopped nil))))
        (should (equal stopped (emacs-agents-session-id (emacs-agents-attention--target queue approval t))))))))

(ert-deftest emacs-agents-attention-sidebar-reveals-only-ancestors-and-retains-unread ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-attention-test-create repo "Deep request" "approval" t "Work/Panels/Harness"))
           (other (emacs-agents-attention-test-create repo "Unread" "input" t "Work Panels")))
      (emacs-agents)
      (setq emacs-agents--collapsed '("Work" "Work/Panels" "Work/Panels/Harness" "Work Panels"))
      (emacs-agents--render-sidebar emacs-agents--ui-sessions)
      (when (bound-and-true-p evil-mode) (evil-motion-state))
      (let ((before (emacs-agents--query "SELECT * FROM sessions")))
        (cl-letf (((symbol-function 'emacs-agents-start) (lambda (&rest _) (ert-fail "Navigation started an agent"))))
          (should (eq (key-binding (kbd "]")) #'emacs-agents-next-attention))
          (call-interactively (key-binding (kbd "]")))
          (should (equal id (emacs-agents--sidebar-id)))
          (should (equal emacs-agents--collapsed '("Work Panels")))
          (should (eq (key-binding (kbd "[")) #'emacs-agents-previous-attention))
          (call-interactively (key-binding (kbd "[")))
          (should (equal other (emacs-agents--sidebar-id)))
          (should-not emacs-agents--collapsed)
          (emacs-agents-next-waiting)
          (should (equal id (emacs-agents--sidebar-id)))
          (emacs-agents-previous-waiting)
          (should (equal id (emacs-agents--sidebar-id)))
          (emacs-agents-next-unread)
          (should (equal other (emacs-agents--sidebar-id)))
          (emacs-agents-previous-unread)
          (should (equal id (emacs-agents--sidebar-id)))
          (emacs-agents--maybe-read-current))
        (should (equal before (emacs-agents--query "SELECT * FROM sessions")))
        (should (zerop (hash-table-count emacs-agents--running)))))))

(ert-deftest emacs-agents-attention-board-scope-and-resolved-request ()
  (emacs-agents-test-with-store
    (let* ((first (emacs-agents-attention-test-create repo "Inside" "approval" nil "Work/Panel"))
           (second (emacs-agents-attention-test-create repo "Unread" "input" t "Work/Panel/Deep"))
           (outside (emacs-agents-attention-test-create repo "Outside" "waiting" nil "Work Panels")))
      (emacs-agents-board)
      (setq emacs-agents-board--scope "Work/Panel" emacs-agents-board--selection second)
      (emacs-agents-board--render)
      (when (bound-and-true-p evil-mode) (evil-motion-state))
      (should (eq (key-binding (kbd "]")) #'emacs-agents-next-attention))
      (call-interactively (key-binding (kbd "]")))
      (should (equal first emacs-agents-board--selection))
      (should (equal first (get-text-property (point) 'emacs-agents-id)))
      (should-not (assoc outside emacs-agents-board--positions))
      (emacs-agents--exec "UPDATE sessions SET activity='input' WHERE id=?" first)
      (emacs-agents-next-attention)
      (should (equal second emacs-agents-board--selection))
      (emacs-agents-next-waiting)
      (should (equal second emacs-agents-board--selection))
      (should (equal "Work/Panel" emacs-agents-board--scope))
      (should (emacs-agents-unread-p (emacs-agents-session second)))
      (emacs-agents-mark-read second)
      (emacs-agents-previous-attention)
      (should (equal second emacs-agents-board--selection)))))

(ert-deftest emacs-agents-attention-dashboard-and-conversation-preserve-drafts ()
  (emacs-agents-test-with-store
    (let* ((id (emacs-agents-attention-test-create repo "Needs input" "waiting" t "Work"))
           (conversation (generate-new-buffer "*Attention draft*")))
      (unwind-protect
          (progn
            (emacs-agents-dashboard)
            ;; Match the command loop after dashboard's pop-to-buffer.
            (set-buffer (window-buffer (selected-window)))
            (when (bound-and-true-p evil-mode) (evil-motion-state))
            (should (eq (key-binding (kbd "]")) #'emacs-agents-next-attention))
            (call-interactively (key-binding (kbd "]")))
            (should (derived-mode-p 'emacs-agents-mode))
            (should (equal id (tabulated-list-get-id)))
            (with-current-buffer conversation
              (setq-local emacs-agents--managed-id id)
              (insert "Unsent draft"))
            (emacs-agents--show-conversation conversation)
            (let ((before (emacs-agents--query "SELECT * FROM sessions")))
              (cl-letf (((symbol-function 'emacs-agents-start) (lambda (&rest _) (ert-fail "Attention started an agent"))))
                (emacs-agents-next-attention))
              (should (derived-mode-p 'emacs-agents-sidebar-mode))
              (should (equal id (emacs-agents--sidebar-id)))
              (should (get-buffer-window conversation))
              (emacs-agents--maybe-read-current)
              (should (equal before (emacs-agents--query "SELECT * FROM sessions")))
              (should (equal "Unsent draft" (with-current-buffer conversation (buffer-string))))))
        (with-current-buffer conversation (set-buffer-modified-p nil))
        (kill-buffer conversation)))))

(ert-deftest emacs-agents-attention-empty-queue-keeps-selection ()
  (emacs-agents-test-with-store
    (emacs-agents-attention-test-create repo "Ready" "input" nil)
    (emacs-agents)
    (let ((id (emacs-agents--sidebar-id)) (layout (current-window-configuration)))
      (emacs-agents-next-attention)
      (emacs-agents-previous-attention)
      (should (equal id (emacs-agents--sidebar-id)))
      (should (compare-window-configurations layout (current-window-configuration))))))

;;; emacs-agents-attention-tests.el ends here
