;;; mx-machina-archive-tests.el --- Record lifecycle tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(unless (boundp 'mx-machina-test-root)
  (load (expand-file-name "mx-machina-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))

(ert-deftest mx-machina-archive-persists-and-restores-without-starting ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Finished work" repo "test" "Work/Project"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "stopped" "unknown" "saved-history")
      (mx-machina--exec "UPDATE sessions SET unread=1,model='known-model' WHERE id=?" id)
      (mx-machina)
      (mx-machina-archive id)
      (should-not (mx-machina-sessions))
      (should (= 1 (length (mx-machina-sessions 'all))))
      (should (equal mx-machina--summary " Agents: 0"))
      (should-not (with-current-buffer "*M-x Machina Sidebar*" (string-match-p "Finished work" (buffer-string))))
      (should-error (mx-machina-start id) :type 'user-error)
      (mx-machina-store-close)
      (let ((session (car (mx-machina-sessions 'archived))))
        (should (mx-machina-archived-p session))
        (should (equal (mx-machina-session-conversation session) "saved-history"))
        (should (equal (mx-machina-session-folder session) "Work/Project"))
        (should (equal (mx-machina-session-model session) "known-model"))
        (should (mx-machina-unread-p session)))
      (mx-machina-archived)
      (goto-char (point-min))
      (when (bound-and-true-p evil-mode) (evil-motion-state))
      (should (eq (key-binding (kbd "RET")) #'mx-machina-restore))
      (should (equal (tabulated-list-get-id) id))
      (cl-letf (((symbol-function 'mx-machina-backend-start)
                 (lambda (&rest _) (ert-fail "Restore must not launch a backend"))))
        (call-interactively (key-binding (kbd "RET"))))
      (should-not (mx-machina-sessions 'archived))
      (should (= 1 (length (mx-machina-sessions))))
      (should (equal (mx-machina-session-run (mx-machina-session id)) run))
      (should (equal (mx-machina-session-status (mx-machina-session id)) "stopped")))))

(ert-deftest mx-machina-v2-migration-preserves-live-observations ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Existing" repo "test"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "live" "working" "saved-history")
      (mx-machina--exec "ALTER TABLE sessions DROP COLUMN archived")
      (mx-machina--exec "PRAGMA user_version=2")
      (mx-machina-store-migrate)
      (mx-machina-store-migrate)
      (let ((session (mx-machina-session id)))
        (should (equal (mx-machina-session-status session) "live"))
        (should (equal (mx-machina-session-conversation session) "saved-history"))
        (should-not (mx-machina-archived-p session))))))

(ert-deftest mx-machina-delete-is-atomic-preserves-files-and-ignores-late-events ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Delete me" repo "test"))
           (run (mx-machina--begin-run id))
           (file (expand-file-name "uncommitted-draft" repo))
           (history (expand-file-name "saved-conversation.jsonl" temporary))
           (buffer (generate-new-buffer "*Retained agent text*")))
      (unwind-protect
          (progn
            (write-region "local draft" nil file nil 'silent)
            (write-region "saved conversation" nil history nil 'silent)
            (mx-machina--observe id run "stopped" "unknown" "saved-history")
            (with-current-buffer buffer
              (insert "Agent text retained")
              (setq-local mx-machina--managed-id id)
              (mx-machina-conversation-mode 1))
            (let ((execute (symbol-function 'mx-machina--exec)))
              (cl-letf (((symbol-function 'mx-machina--exec)
                         (lambda (sql &rest values)
                           (if (equal sql "DELETE FROM sessions WHERE id=?")
                               (error "Simulated deletion failure")
                             (apply execute sql values)))))
                (should-error (mx-machina-delete id))))
            (should (mx-machina-session id))
            (should (mx-machina--query "SELECT id FROM runs WHERE session=?" id))
            (mx-machina-delete id)
            (should-not (mx-machina-session id t))
            (should-not (mx-machina--query "SELECT id FROM runs WHERE session=?" id))
            (should-not (mx-machina--observe id run "live" "working" "saved-history"))
            (should (file-readable-p file))
            (should (file-readable-p history))
            (should (equal (mx-machina--git repo "branch" "--show-current") "main"))
            (with-current-buffer buffer
              (should (equal (buffer-string) "Agent text retained"))
              (should-not mx-machina--managed-id)
              (should-not mx-machina-conversation-mode)))
        (when (buffer-live-p buffer) (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))))))

(ert-deftest mx-machina-removal-cancellation-does-not-stop-or-change-records ()
  (mx-machina-test-with-store
    (let ((id (mx-machina-create "Running" repo "test")))
      (puthash id '(fake-run . fake-transport) mx-machina--running)
      (unwind-protect
          (cl-letf (((symbol-function 'mx-machina--read-id) (lambda () id))
                    ((symbol-function 'y-or-n-p) (lambda (&rest _) nil))
                    ((symbol-function 'yes-or-no-p) (lambda (&rest _) nil))
                    ((symbol-function 'mx-machina-stop) (lambda (&rest _) (ert-fail "Must not stop on cancellation"))))
            (should-error (call-interactively #'mx-machina-archive) :type 'user-error)
            (should-error (call-interactively #'mx-machina-delete) :type 'user-error)
            (should-error (mx-machina-archive id) :type 'user-error)
            (should-error (mx-machina-delete id) :type 'user-error)
            (should-not (mx-machina-archived-p (mx-machina-session id)))
            (should (gethash id mx-machina--running)))
        (remhash id mx-machina--running)))))
