;;; mx-machina-actions-tests.el --- Contextual menu tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(unless (boundp 'mx-machina-test-root)
  (load (expand-file-name "mx-machina-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))
(require 'mx-machina-actions)
(require 'mx-machina-board)

(ert-deftest mx-machina-actions-ui-open-close-is-read-only ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Menu target" repo "test"))
           (before (mx-machina--query "SELECT * FROM sessions")))
      (mx-machina)
      (when (bound-and-true-p evil-mode) (evil-motion-state))
      (should (eq (key-binding (kbd "?")) #'mx-machina-actions))
      (let ((layout (current-window-configuration)))
        (cl-letf (((symbol-function 'mx-machina-start) (lambda (&rest _) (ert-fail "Menu launched an agent"))))
          (call-interactively (key-binding (kbd "?")))
          (when (bound-and-true-p evil-mode) (evil-motion-state))
          (should (equal id mx-machina-actions--id))
          (should (string-match-p "No tracked process" (buffer-string)))
          (should buffer-read-only)
          (should-not mx-machina--managed-id)
          (should (eq (key-binding (kbd "q")) #'mx-machina-actions-close))
          (mx-machina--maybe-read-current)
          (call-interactively (key-binding (kbd "q"))))
        (should (compare-window-configurations layout (current-window-configuration))))
      (should (equal before (mx-machina--query "SELECT * FROM sessions"))))))

(ert-deftest mx-machina-actions-state-availability-and-revalidation ()
  (mx-machina-test-with-store
    (let ((id (mx-machina-create "State" repo "test")))
      (mx-machina)
      (mx-machina-actions)
      (let ((rows (mx-machina-actions--entries (mx-machina-actions--session))))
        (should-not (nth 3 (assoc "o" rows)))
        (should (nth 3 (assoc "x" rows)))
        (should (nth 3 (assoc "r" rows))))
      (mx-machina--exec "UPDATE sessions SET archived=1 WHERE id=?" id)
      (cl-letf (((symbol-function 'mx-machina-open) (lambda (&rest _) (ert-fail "Archived agent opened"))))
        (should-error (mx-machina-actions--run "o") :type 'user-error))
      (should (string-match-p "Restore this archived" (buffer-string)))
      (should-not (nth 3 (assoc "s" (mx-machina-actions--entries (mx-machina-actions--session)))))
      (mx-machina-actions--run "s")
      (should-not (mx-machina-archived-p (mx-machina-session id)))
      (should (zerop (hash-table-count mx-machina--running)))
      (mx-machina-actions)
      (let ((before (mx-machina--query "SELECT * FROM sessions")))
        (should-error (mx-machina-actions--run "u") :type 'user-error)
        (should (equal before (mx-machina--query "SELECT * FROM sessions"))))
      (mx-machina--exec "DELETE FROM sessions WHERE id=?" id)
      (should-error (mx-machina-actions--run "i") :type 'user-error)
      (should (string-match-p "Agent record deleted" (buffer-string))))))

(ert-deftest mx-machina-actions-pin-target-and-retain-delete-confirmation ()
  (mx-machina-test-with-store
    (let ((first (mx-machina-create "First" repo "test"))
          (second (mx-machina-create "Second" repo "test")))
      (mx-machina)
      (mx-machina-actions)
      (with-current-buffer "*M-x Machina Sidebar*" (goto-char (mx-machina--sidebar-position second)))
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "Renamed first")))
        (mx-machina-actions--run "R"))
      (should (equal "Renamed first" (mx-machina-session-name (mx-machina-session first))))
      (should (equal "Second" (mx-machina-session-name (mx-machina-session second))))
      (mx-machina-actions)
      (let ((before (mx-machina--query "SELECT * FROM sessions")) prompted)
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (prompt) (setq prompted prompt) nil)))
          (should-error (mx-machina-actions--run "d") :type 'user-error))
        (should (string-match-p "Renamed first" prompted))
        (should (equal before (mx-machina--query "SELECT * FROM sessions")))))))

(ert-deftest mx-machina-actions-running-archive-cancellation-does-not-stop ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Running" repo "test"))
           (run (mx-machina--begin-run id))
           (buffer (generate-new-buffer "*Menu running fixture*"))
           (transport (mx-machina--transport-create :buffer buffer)))
      (unwind-protect
          (progn
            (puthash id (cons run transport) mx-machina--running)
            (mx-machina)
            (mx-machina-actions)
            (let ((rows (mx-machina-actions--entries (mx-machina-actions--session))))
              (should-not (nth 3 (assoc "o" rows)))
              (should-not (nth 3 (assoc "x" rows)))
              (should (nth 3 (assoc "W" rows)))
              (should (equal "Stop and archive…" (nth 1 (assoc "a" rows)))))
            (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) nil))
                      ((symbol-function 'mx-machina-stop) (lambda (&rest _) (ert-fail "Cancelled archive stopped agent"))))
              (should-error (mx-machina-actions--run "a") :type 'user-error))
            (should (gethash id mx-machina--running))
            (should-not (mx-machina-archived-p (mx-machina-session id))))
        (remhash id mx-machina--running)
        (kill-buffer buffer)))))

(ert-deftest mx-machina-actions-ui-key-dispatch-and-board-return ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Board card" repo "test"))
           (conversation (generate-new-buffer "*Menu conversation*")))
      (unwind-protect
          (progn
            (with-current-buffer conversation
              (setq-local mx-machina--managed-id id)
              (insert "Unsent draft"))
            (mx-machina-board)
            (when (bound-and-true-p evil-mode) (evil-motion-state))
            (call-interactively (key-binding (kbd "?")))
            (when (bound-and-true-p evil-mode) (evil-motion-state))
            (cl-letf (((symbol-function 'mx-machina-start) (lambda (selected) (should (equal id selected)) conversation)))
              (execute-kbd-macro (kbd "o")))
            (should (eq (window-buffer (selected-window)) conversation))
            (should-not (get-buffer-window "*M-x Machina Actions*"))
            (mx-machina-close-view)
            (should (get-buffer-window "*M-x Machina Board*"))
            (with-current-buffer "*M-x Machina Board*" (should (equal id mx-machina-board--selection)))
            (should (equal "Unsent draft" (with-current-buffer conversation (buffer-string)))))
        (with-current-buffer conversation (set-buffer-modified-p nil))
        (kill-buffer conversation)))))

(ert-deftest mx-machina-actions-empty-and-folder-context ()
  (mx-machina-test-with-store
    (let ((origin (current-buffer)))
      (mx-machina-actions)
      (should-not (file-exists-p mx-machina-directory))
      (should (nth 3 (assoc "o" (mx-machina-actions--entries nil))))
      (should-not (nth 3 (assoc "n" (mx-machina-actions--entries nil))))
      (mx-machina-actions-close)
      (should (eq origin (current-buffer))))
    (mx-machina-folder-create "Work")
    (mx-machina)
    (mx-machina-actions)
    (should (equal "Work" mx-machina-actions--folder))
    (should-not (nth 3 (assoc "TAB" (mx-machina-actions--entries nil))))
    (mx-machina-actions--run "TAB")
    (should (member "Work" mx-machina--collapsed))))

;;; mx-machina-actions-tests.el ends here
