;;; mx-machina-transcript-tests.el --- Transcript copy view tests -*- lexical-binding: t; -*-
(require 'mx-machina-transcript)
(unless (boundp 'mx-machina-test-root)
  (load (expand-file-name "mx-machina-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))

(ert-deftest mx-machina-transcript-copy-view-retains-text-and-source ()
  (mx-machina-test-with-store
    (let* ((account (expand-file-name "account" temporary))
           (project (expand-file-name "projects/fixture" account))
           (file (expand-file-name "saved-id.jsonl" project))
           (mx-machina-eat-profiles `(((:identifier . test-eat)
                                        (:environment . (,(concat "CLAUDE_CONFIG_DIR=" account))))))
           (id (mx-machina-create "Reading" repo "test-eat"))
           (run (mx-machina--begin-run id))
           (source (get-buffer-create "*Transcript source test*")))
      (make-directory project t)
      (with-temp-file file
        (dolist (row '(((type . "user") (uuid . "1") (message . ((content . "My question"))))
                       ((type . "assistant") (uuid . "2") (message . ((content . [((type . "text") (text . "First line\nSecond line"))]))))
                       ((type . "assistant") (uuid . "2") (message . ((content . [((type . "text") (text . "duplicate"))]))))
                       ((type . "user") (message . ((content . [((type . "tool_result") (content . "tool output"))]))))))
          (insert (json-encode row) "\n"))
        (insert "{\"partial\":"))
      (mx-machina--observe id run "live" "input" "saved-id")
      (with-current-buffer source (setq-local mx-machina--managed-id id))
      (mx-machina--show-conversation source)
      (mx-machina-transcript)
      (should (derived-mode-p 'mx-machina-transcript-mode))
      (should buffer-read-only)
      (should (equal (buffer-string) "You\n\nMy question\n\nClaude\n\nFirst line\nSecond line\n\n"))
      (should-not (mx-machina--conversation-reading-p (current-buffer)))
      (let ((transport (mx-machina--transport-create))
            (text (buffer-string)) (position (point)))
        (puthash id (cons run transport) mx-machina--running)
        (unwind-protect
            (progn
              (run-hook-with-args 'mx-machina-backend-event-hook transport 'message nil)
              (should mx-machina-transcript--stale)
              (should (equal text (buffer-string)))
              (should (= position (point)))
              (mx-machina-transcript-refresh)
              (should-not mx-machina-transcript--stale))
          (remhash id mx-machina--running)))
      (when (bound-and-true-p evil-mode)
        (evil-normal-state)
        (search-forward "First line")
        (beginning-of-line)
        (execute-kbd-macro (kbd "V j y"))
        (should (string-match-p "First line\nSecond line" (current-kill 0))))
      (mx-machina-transcript-return)
      (should (eq (current-buffer) source))
      (should (equal (mx-machina-session-conversation (mx-machina-session id)) "saved-id"))
      (let ((session (mx-machina-session id))
            (mx-machina-vterm-profiles 'inherit))
        (setf (mx-machina-session-profile session) "test-eat-vterm")
        (should (equal (mx-machina-transcript--file session) file))))))

(ert-deftest mx-machina-transcript-omits-command-envelopes ()
  (mx-machina-test-with-store
    (let ((file (expand-file-name "envelopes.jsonl" temporary)))
      (with-temp-file file
        (dolist (tag '("task-notification" "command-name" "command-message" "bash-input"
                       "bash-stdout" "local-command-stdout" "bash-stderr"))
          (insert (json-encode `((type . "user") (message . ((content . ,(format " <%s>noise</%s>" tag tag)))))) "\n"))
        (dolist (row '(((type . "user") (message . ((content . "Explain <bash-input> please"))))
                       ((type . "assistant") (message . ((content . "<bash-input>example</bash-input>"))))))
          (insert (json-encode row) "\n")))
      (should (equal (mx-machina-transcript--text file)
                     "You\n\nExplain <bash-input> please\n\nClaude\n\n<bash-input>example</bash-input>\n\n")))))
