;;; mx-machina-attention-tests.el --- Attention navigation tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(unless (boundp 'mx-machina-test-root)
  (load (expand-file-name "mx-machina-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))
(require 'mx-machina-attention)
(require 'mx-machina-board)

(defun mx-machina-attention-test-create (repo name state unread &optional folder)
  "Create a fixture in REPO named NAME with STATE, UNREAD and FOLDER."
  (let* ((id (mx-machina-create name repo "test" folder))
         (run (mx-machina--begin-run id)))
    (mx-machina--observe id run (if (equal state "stopped") "stopped" "live") state "saved")
    (when unread (mx-machina--exec "UPDATE sessions SET unread=1 WHERE id=?" id))
    id))

(ert-deftest mx-machina-attention-priority-wrap-dedup-and-exclusions ()
  (mx-machina-test-with-store
    (let* ((unread (mx-machina-attention-test-create repo "Old unread" "input" t))
           (approval (mx-machina-attention-test-create repo "Approval and unread" "approval" t))
           (waiting (mx-machina-attention-test-create repo "Question" "waiting" nil))
           (stopped (mx-machina-attention-test-create repo "Stopped unread" "stopped" t))
           (archived (mx-machina-attention-test-create repo "Archived" "approval" t)))
      (mx-machina-attention-test-create repo "Idle" "input" nil)
      (mx-machina-attention-test-create repo "Busy" "working" nil)
      (mx-machina-archive archived)
      (let* ((sessions (mx-machina-sessions 'all))
             (queue (mx-machina-attention--queue sessions 'all)))
        (should (equal (mapcar #'mx-machina-session-id queue) (list approval waiting unread stopped)))
        (should (equal (mapcar #'mx-machina-session-id (mx-machina-attention--queue sessions 'waiting))
                       (list approval waiting)))
        (should (equal (mapcar #'mx-machina-session-id (mx-machina-attention--queue sessions 'unread))
                       (list unread approval stopped)))
        (dolist (previous '(nil t))
          (should (equal approval (mx-machina-session-id (mx-machina-attention--target queue nil previous)))))
        (should (equal approval (mx-machina-session-id (mx-machina-attention--target queue stopped nil))))
        (should (equal stopped (mx-machina-session-id (mx-machina-attention--target queue approval t))))))))

(ert-deftest mx-machina-attention-sidebar-reveals-only-ancestors-and-retains-unread ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-attention-test-create repo "Deep request" "approval" t "Work/Panels/Harness"))
           (other (mx-machina-attention-test-create repo "Unread" "input" t "Work Panels")))
      (mx-machina)
      (setq mx-machina--collapsed '("Work" "Work/Panels" "Work/Panels/Harness" "Work Panels"))
      (mx-machina--render-sidebar mx-machina--ui-sessions)
      (when (bound-and-true-p evil-mode) (evil-motion-state))
      (let ((before (mx-machina--query "SELECT * FROM sessions")))
        (cl-letf (((symbol-function 'mx-machina-start) (lambda (&rest _) (ert-fail "Navigation started an agent"))))
          (should (eq (key-binding (kbd "]")) #'mx-machina-next-attention))
          (call-interactively (key-binding (kbd "]")))
          (should (equal id (mx-machina--sidebar-id)))
          (should (equal mx-machina--collapsed '("Work Panels")))
          (should (eq (key-binding (kbd "[")) #'mx-machina-previous-attention))
          (call-interactively (key-binding (kbd "[")))
          (should (equal other (mx-machina--sidebar-id)))
          (should-not mx-machina--collapsed)
          (mx-machina-next-waiting)
          (should (equal id (mx-machina--sidebar-id)))
          (mx-machina-previous-waiting)
          (should (equal id (mx-machina--sidebar-id)))
          (mx-machina-next-unread)
          (should (equal other (mx-machina--sidebar-id)))
          (mx-machina-previous-unread)
          (should (equal id (mx-machina--sidebar-id)))
          (mx-machina--maybe-read-current))
        (should (equal before (mx-machina--query "SELECT * FROM sessions")))
        (should (zerop (hash-table-count mx-machina--running)))))))

(ert-deftest mx-machina-attention-board-scope-and-resolved-request ()
  (mx-machina-test-with-store
    (let* ((first (mx-machina-attention-test-create repo "Inside" "approval" nil "Work/Panel"))
           (second (mx-machina-attention-test-create repo "Unread" "input" t "Work/Panel/Deep"))
           (outside (mx-machina-attention-test-create repo "Outside" "waiting" nil "Work Panels")))
      (mx-machina-board)
      (setq mx-machina-board--scope "Work/Panel" mx-machina-board--selection second)
      (mx-machina-board--render)
      (when (bound-and-true-p evil-mode) (evil-motion-state))
      (should (eq (key-binding (kbd "]")) #'mx-machina-next-attention))
      (call-interactively (key-binding (kbd "]")))
      (should (equal first mx-machina-board--selection))
      (should (equal first (get-text-property (point) 'mx-machina-id)))
      (should-not (assoc outside mx-machina-board--positions))
      (mx-machina--exec "UPDATE sessions SET activity='input' WHERE id=?" first)
      (mx-machina-next-attention)
      (should (equal second mx-machina-board--selection))
      (mx-machina-next-waiting)
      (should (equal second mx-machina-board--selection))
      (should (equal "Work/Panel" mx-machina-board--scope))
      (should (mx-machina-unread-p (mx-machina-session second)))
      (mx-machina-mark-read second)
      (mx-machina-previous-attention)
      (should (equal second mx-machina-board--selection)))))

(ert-deftest mx-machina-attention-dashboard-and-conversation-preserve-drafts ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-attention-test-create repo "Needs input" "waiting" t "Work"))
           (conversation (generate-new-buffer "*Attention draft*")))
      (unwind-protect
          (progn
            (mx-machina-dashboard)
            ;; Match the command loop after dashboard's pop-to-buffer.
            (set-buffer (window-buffer (selected-window)))
            (when (bound-and-true-p evil-mode) (evil-motion-state))
            (should (eq (key-binding (kbd "]")) #'mx-machina-next-attention))
            (call-interactively (key-binding (kbd "]")))
            (should (derived-mode-p 'mx-machina-mode))
            (should (equal id (tabulated-list-get-id)))
            (with-current-buffer conversation
              (setq-local mx-machina--managed-id id)
              (insert "Unsent draft"))
            (mx-machina--show-conversation conversation)
            (let ((before (mx-machina--query "SELECT * FROM sessions")))
              (cl-letf (((symbol-function 'mx-machina-start) (lambda (&rest _) (ert-fail "Attention started an agent"))))
                (mx-machina-next-attention))
              (should (derived-mode-p 'mx-machina-sidebar-mode))
              (should (equal id (mx-machina--sidebar-id)))
              (should (get-buffer-window conversation))
              (mx-machina--maybe-read-current)
              (should (equal before (mx-machina--query "SELECT * FROM sessions")))
              (should (equal "Unsent draft" (with-current-buffer conversation (buffer-string))))))
        (with-current-buffer conversation (set-buffer-modified-p nil))
        (kill-buffer conversation)))))

(ert-deftest mx-machina-attention-empty-queue-keeps-selection ()
  (mx-machina-test-with-store
    (mx-machina-attention-test-create repo "Ready" "input" nil)
    (mx-machina)
    (let ((id (mx-machina--sidebar-id)) (layout (current-window-configuration)))
      (mx-machina-next-attention)
      (mx-machina-previous-attention)
      (should (equal id (mx-machina--sidebar-id)))
      (should (compare-window-configurations layout (current-window-configuration))))))

;;; mx-machina-attention-tests.el ends here
