;;; mx-machina-tests.el --- Registry and lifecycle tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(require 'ert)
(require 'mx-machina)

(defconst mx-machina-test-root
  (file-name-directory (directory-file-name (file-name-directory (or load-file-name buffer-file-name)))))

(defmacro mx-machina-test-with-store (&rest body)
  "Run BODY with an isolated registry and committed Git worktree."
  (declare (indent 0) (debug t))
  `(let* ((temporary (make-temp-file "mx-machina-test-" t))
          (user-emacs-directory (expand-file-name "emacs/" temporary))
          (mx-machina-directory (expand-file-name "state/" temporary))
          (mx-machina--db nil) (mx-machina--db-file nil)
          (mx-machina--running (make-hash-table :test #'equal))
          (mx-machina--timer nil)
          (mx-machina--ui-timer nil)
          (mx-machina--read-dwell nil)
          (mx-machina--ui-sessions nil)
          (mx-machina--ui-folders nil)
          (mx-machina--active-session nil)
          (mx-machina--conversation-buffers nil)
          (global-mode-string nil)
          (mx-machina-status-mode nil)
          (repo (expand-file-name "worktree/" temporary)))
     (unwind-protect
         (save-window-excursion
           (make-directory repo)
           (mx-machina--git repo "init" "-b" "main")
           (mx-machina--git repo "-c" "user.name=Fixture" "-c" "user.email=fixture@example.invalid"
                              "-c" "commit.gpgsign=false" "commit" "--allow-empty" "-m" "Fixture")
           ,@body)
       (mx-machina-shutdown)
       (set-frame-parameter nil 'mx-machina-focus-layout nil)
       (set-frame-parameter nil 'mx-machina-conversation-layout nil)
       (dolist (buffer (buffer-list))
         (when (or (member (buffer-name buffer) '("*M-x Machina*" "*M-x Machina Sidebar*" "*M-x Machina Archive*"))
                   (memq (buffer-local-value 'major-mode buffer) '(mx-machina-diagnostics-mode mx-machina-board-mode mx-machina-actions-mode))
                   (buffer-local-value 'mx-machina--managed-id buffer))
           (with-current-buffer buffer (set-buffer-modified-p nil))
           (let ((kill-buffer-query-functions nil)) (kill-buffer buffer))))
       (delete-directory temporary t))))

(ert-deftest mx-machina-new-worktree-persists-isolated-session ()
  (mx-machina-test-with-store
    (let ((path (expand-file-name "agent checkout" temporary))
          (commit (mx-machina--git repo "rev-parse" "HEAD")))
      (write-region "local work" nil (expand-file-name "draft" repo) nil 'silent)
      (let* ((id (mx-machina-create-worktree "Harness" repo "test" "agent/harness" path "Work/Project")))
        (mx-machina-store-close)
        (let ((session (mx-machina-session id)))
          (should (equal (mx-machina-session-directory session)
                         (file-name-as-directory (file-truename path))))
          (should (equal (mx-machina-session-branch session) "agent/harness"))
          (should (equal (mx-machina-session-project session) "worktree"))
          (should (equal (mx-machina-session-folder session) "Work/Project"))
          (should (equal (mx-machina-session-status session) "stopped"))
          (should-not (mx-machina-session-run session)))
        (should (equal (mx-machina--git path "rev-parse" "HEAD") commit))
        (should (equal (mx-machina--git repo "branch" "--show-current") "main"))
        (should (equal (mx-machina--git repo "status" "--porcelain") "?? draft"))
        (should-not (file-exists-p (expand-file-name "draft" path)))
        (should (zerop (hash-table-count mx-machina--running)))))))

(ert-deftest mx-machina-new-worktree-rejects-collisions-and-invalid-input ()
  (mx-machina-test-with-store
    (let ((path (expand-file-name "new-worktree" temporary)))
      (dolist (branch '("main" "invalid branch" "--bad"))
        (should-error (mx-machina-create-worktree "Test" repo "test" branch path)
                      :type 'user-error)
        (should-not (file-exists-p path)))
      (should-error (mx-machina-create-worktree "" repo "test" "new" path) :type 'user-error)
      (should-error (mx-machina-create-worktree "Test" repo "" "new" path) :type 'user-error)
      (make-directory path)
      (write-region "keep me" nil (expand-file-name "existing" path) nil 'silent)
      (should-error (mx-machina-create-worktree "Test" repo "test" "new" path) :type 'user-error)
      (should (file-exists-p (expand-file-name "existing" path)))
      (should (equal (mx-machina--git repo "branch" "--format=%(refname:short)") "main"))
      (should-not (mx-machina-sessions)))))

(ert-deftest mx-machina-new-worktree-save-failure-reports-retained-checkout ()
  (mx-machina-test-with-store
    (let ((path (expand-file-name "retained" temporary)))
      (cl-letf (((symbol-function 'mx-machina-create)
                 (lambda (&rest _) (error "Simulated registry failure"))))
        (let ((err (should-error
                    (mx-machina-create-worktree "Test" repo "test" "agent/test" path))))
          (should (string-match-p "Worktree created at" (error-message-string err)))
          (should (string-match-p (regexp-quote path) (error-message-string err)))))
      (should (equal (cadr (mx-machina--worktree path)) "agent/test"))
      (should-not (mx-machina-sessions)))))

(ert-deftest mx-machina-new-session-prompts-defer-worktree-creation ()
  (mx-machina-test-with-store
    (dolist (create '(nil t))
      (let ((path (expand-file-name "prompted" temporary)))
        (cl-letf (((symbol-function 'read-string)
                   (lambda (prompt &rest _) (if (equal prompt "Session name: ") "Test" "agent/test")))
                  ((symbol-function 'read-directory-name)
                   (lambda (prompt &rest _)
                     (if (equal prompt "Git repository or worktree: ") repo path)))
                  ((symbol-function 'y-or-n-p) (lambda (&rest _) create))
                  ((symbol-function 'mx-machina-backend-read-profile) (lambda () "test"))
                  ((symbol-function 'completing-read) (lambda (&rest _) "test"))
                  ((symbol-function 'mx-machina--read-folder) (lambda () "Work")))
          (let ((args (mx-machina--read-new-session)))
            (should (equal (nth 4 args) (and create (list "agent/test" path))))
            (should-not (file-exists-p path))
            (should-not (mx-machina-sessions)))
          (cl-letf (((symbol-function 'mx-machina--read-folder) (lambda () (signal 'quit nil))))
            (should (eq (condition-case nil (mx-machina--read-new-session)
                          (quit 'cancelled)) 'cancelled)))
          (should-not (file-exists-p path))
          (should (equal (mx-machina--git repo "branch" "--format=%(refname:short)") "main")))))))

(ert-deftest mx-machina-profile-picker-separates-account-and-interface ()
  (let ((mx-machina-eat-profiles
         '(((:identifier . claude-work) (:agent . "Claude") (:account . "work") (:command . ("claude")))
           ((:identifier . claude-home) (:agent . "Claude") (:account . "home") (:command . ("claude")))))
        (mx-machina-vterm-profiles 'inherit)
        offered)
    (cl-letf (((symbol-function 'mx-machina-agent-shell-configs)
               (lambda () '(((:identifier . claude-acp-work) (:agent . "Claude") (:account . "work")))))
              ((symbol-function 'completing-read)
               (lambda (prompt choices &rest _)
                 (push (cons prompt choices) offered)
                 (pcase prompt ("Agent: " "Claude") ("Account: " "work") ("Interface: " "vterm")))))
      (should (equal (mx-machina-backend-read-profile) "claude-work-vterm"))
      (should (equal (sort (copy-sequence (cdr (assoc "Interface: " offered))) #'string<)
                     '("agent-shell" "eat" "vterm")))
      (should-not (map-elt (car mx-machina-eat-profiles) :interface))
      (should (equal (map-elt (car mx-machina-eat-profiles) :identifier) 'claude-work))
      (let ((mx-machina-vterm-profiles '(((:identifier . claude-work)))))
        (should-error (mx-machina-backend-configs) :type 'user-error)))))

(ert-deftest mx-machina-eshell-is-associated-reused-and-independent ()
  (mx-machina-test-with-store
    (let* ((first (mx-machina-create "Harness" repo "test"))
           (second (mx-machina-create "Migration" repo "test"))
           (initial-count (hash-table-count mx-machina--running))
           first-buffer second-buffer)
      (unwind-protect
          (progn
            (mx-machina)
            (setq first-buffer (mx-machina-eshell first))
            (should (derived-mode-p 'eshell-mode))
            (should (equal (file-truename default-directory) (file-truename repo)))
            (should-not mx-machina--managed-id)
            (insert "echo unsent draft")
            (setq second-buffer (mx-machina-eshell second))
            (should-not (eq first-buffer second-buffer))
            (should (eq first-buffer (mx-machina-eshell first)))
            (should (string-suffix-p "echo unsent draft" (buffer-string)))
            (should (= (length (window-list)) 2))
            (should (= initial-count (hash-table-count mx-machina--running)))
            (should (equal (mx-machina-session-status (mx-machina-session first)) "stopped")))
        (dolist (buffer (list first-buffer second-buffer))
          (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest mx-machina-registry-persists-identity-and-recovers-status ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "O'Brien" repo "test-account"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "live" "working" "conversation-123")
      (mx-machina-store-close)
      (let ((session (mx-machina-session id)))
        (should (equal (mx-machina-session-name session) "O'Brien"))
        (should (equal (mx-machina-session-conversation session) "conversation-123"))
        (should (equal (mx-machina-session-profile session) "test-account"))
        (should (equal (mx-machina-session-status session) "stopped"))
        (should (equal (mx-machina-session-activity session) "unknown")))
      (should (equal (caar (mx-machina--query "SELECT outcome FROM runs WHERE id=?" run)) "disconnected")))))

(ert-deftest mx-machina-stale-and-terminal-events-cannot-resurrect-runs ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Test" repo "test"))
           (old (mx-machina--begin-run id)))
      (mx-machina--observe id old "stopped" "unknown" "conversation")
      (let ((new (mx-machina--begin-run id)))
        (should-not (mx-machina--observe id old "live" "working"))
        (mx-machina--observe id new "failed" "unknown" nil "Resume failed")
        (should-not (mx-machina--observe id new "live" "input"))
        (should (equal (mx-machina-session-status (mx-machina-session id)) "failed"))))))

(ert-deftest mx-machina-conversation-mismatch-preserves-original ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Test" repo "test"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "live" "input" "original")
      (should-error (mx-machina--observe id run "live" "input" "replacement"))
      (should (equal (mx-machina-session-conversation (mx-machina-session id)) "original")))))

(ert-deftest mx-machina-branch-change-blocks-launch ()
  (mx-machina-test-with-store
    (let ((id (mx-machina-create "Test" repo "test")))
      (mx-machina--git repo "checkout" "-b" "different")
      (should-error (mx-machina-start id) :type 'user-error)
      (should-not (mx-machina-session-run (mx-machina-session id))))))

(ert-deftest mx-machina-unconfirmed-identity-blocks-replacement ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Test" repo "test"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "stopped" "unknown")
      (should-error (mx-machina-start id) :type 'user-error))))

(ert-deftest mx-machina-dashboard-is-read-only-and-does-not-launch ()
  (mx-machina-test-with-store
    (let ((id (mx-machina-create "Test" repo "test")))
      (mx-machina-dashboard)
      (with-current-buffer "*M-x Machina*"
        (should buffer-read-only)
        (should (equal (caar tabulated-list-entries) id))
        (should (string-match-p "Test" (buffer-string))))
      (should (zerop (hash-table-count mx-machina--running)))
      (should-not (mx-machina-session-run (mx-machina-session id))))))

(ert-deftest mx-machina-guard-rejects-fallback-and-wrong-conversations ()
  (dolist (request '(((:method . "session/new"))
                     ((:method . "session/fork") (:params . ((sessionId . "original"))))
                     ((:method . "session/load") (:params . ((sessionId . "wrong"))))
                     ((:method . "session/resume") (:params . ((sessionId . "wrong"))))
                     ((:method . "session/prompt") (:params . ((sessionId . "wrong"))))))
    (let* (failure
           (transport (mx-machina--transport-create
                       :conversation "original"
                       :callback (lambda (&rest args) (setq failure args)))))
      (should-error (mx-machina--guard-request transport request))
      (should (equal (car failure) "failed")))))

(ert-deftest mx-machina-guard-allows-only-saved-resume ()
  (let* ((transport (mx-machina--transport-create :conversation "saved"))
         (request '((:method . "session/load") (:params . ((sessionId . "saved"))))))
    (should (eq request (mx-machina--guard-request transport request)))))

(ert-deftest mx-machina-guard-allows-metadata-list-before-and-after-ready ()
  (dolist (ready '(nil t))
    (let* ((transport (mx-machina--transport-create :conversation "saved" :ready ready))
           (request '((:method . "session/list") (:params . ((cwd . "/fixture"))))))
      (should (eq request (mx-machina--guard-request transport request)))
      (should-not (mx-machina-transport-failed transport))
      (should (equal (mx-machina-transport-conversation transport) "saved")))))

(ert-deftest mx-machina-refuses-newer-schema ()
  (mx-machina-test-with-store
    (mx-machina--exec "PRAGMA user_version=99")
    (mx-machina-store-close)
    (should-error (mx-machina-store-open))
    (should-not mx-machina--db)))

(ert-deftest mx-machina-sidebar-preserves-selection-and-does-not-launch ()
  (mx-machina-test-with-store
    (let* ((first (mx-machina-create "First" repo "test"))
           (second (mx-machina-create "Second" repo "test")))
      (mx-machina)
      (should (eq (window-parameter nil 'window-side) 'left))
      (should buffer-read-only)
      (should (equal (mx-machina--sidebar-id) first))
      (mx-machina-sidebar-next)
      (should (equal (mx-machina--read-id) second))
      (mx-machina-sidebar-expand)
      (forward-line 2)
      (let ((position (point)) (window (selected-window)))
        (mx-machina-refresh)
        (should (eq window (selected-window)))
        (should (= position (point)))
        (should (equal (mx-machina--sidebar-id) second))
        (should (string-match-p "Profile: test" (buffer-string))))
      (mx-machina-sidebar-previous)
      (should (equal (mx-machina--sidebar-id) first))
      (mx-machina-sidebar-previous)
      (should (equal (mx-machina--sidebar-id) first))
      (should (zerop (hash-table-count mx-machina--running)))
      (should-not (mx-machina-session-run (mx-machina-session second)))
      (should (string-match-p "2 stopped" mx-machina--summary)))))

(ert-deftest mx-machina-counts-honor-process-state-and-unknown-activity ()
  (let ((global-mode-string '("existing"))
        (mx-machina-status-mode nil))
    (mx-machina--refresh-ui
     (mapcar (lambda (pair)
               (mx-machina--session-create :status (car pair) :activity (cdr pair)))
             '(("live" . "working") ("live" . "working") ("live" . "input")
               ("live" . "approval") ("live" . "unrecognized")
               ("starting" . "input") ("stopped" . "working")
               ("exited" . "approval") ("failed" . "input"))))
    (should (equal (substring-no-properties mx-machina--summary)
                   " Agents: 2 working · 1 ready · 1 approval · 1 starting · 2 stopped · 1 unknown · 1 error"))
    (mx-machina-status-mode 1)
    (mx-machina-status-mode 1)
    (should (equal global-mode-string '("existing" mx-machina--summary)))
    (mx-machina-status-mode -1)
    (should (equal global-mode-string '("existing")))))

(ert-deftest mx-machina-conversations-use-main-area-and-reuse-window ()
  (mx-machina-test-with-store
    (let ((id (mx-machina-create "Test" repo "test"))
          (first (generate-new-buffer "*Agent test first*"))
          (second (generate-new-buffer "*Agent test second*")))
      (dolist (buffer (list first second))
        (with-current-buffer buffer
          (setq-local mx-machina--managed-id id)))
      (with-current-buffer first (insert "unsent draft"))
      (mx-machina--show-conversation first)
      (let ((pane (selected-window))
            (overview (get-buffer-window "*M-x Machina Sidebar*")))
        (should-not (window-parameter pane 'window-side))
        (should (= (length (window-list)) 2))
        (mx-machina--show-conversation second)
        (should (eq pane (selected-window)))
        (mx-machina--select-main-window)
        (switch-to-buffer (get-buffer-create "*scratch*"))
        (delete-other-windows)
        (should (window-live-p overview))
        (should (window-live-p pane))
        (mx-machina--show-conversation first)
        (should (equal (buffer-string) "unsent draft"))
        (let ((position (point)))
          (mx-machina-refresh)
          (should (eq pane (selected-window)))
          (should (= position (point))))))))

(ert-deftest mx-machina-focus-restores-layout-and-retains-draft ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Test" repo "test"))
           (conversation (generate-new-buffer "*Agent focus test*")))
      (with-current-buffer conversation
        (setq-local mx-machina--managed-id id)
        (mx-machina-conversation-mode 1)
        (insert "draft"))
      (mx-machina--show-conversation conversation)
      (mx-machina--select-main-window)
      (split-window-right)
      (select-window (get-buffer-window "*M-x Machina Sidebar*"))
      (let ((before (current-window-configuration))
            (selection (selected-window)))
        (cl-letf (((symbol-function 'mx-machina-start) (lambda (_id) conversation)))
          (mx-machina-focus id)
          (should (= (length (window-list)) 1))
          (should (eq (current-buffer) conversation))
          (should (eq (key-binding (kbd "C-c C-z")) #'mx-machina-focus))
          (should (memq 'mx-machina--summary global-mode-string))
          (goto-char (point-max))
          (insert " continued")
          (mx-machina-refresh)
          (should (= (length (window-list)) 1))
          (mx-machina-focus)
          (should-not (frame-parameter nil 'mx-machina-focus-layout))
          (should (compare-window-configurations before (current-window-configuration)))
          (should (eq selection (selected-window)))
          (should (equal (with-current-buffer conversation (buffer-string)) "draft continued"))
          ;; Focusing from the conversation must work too.
          (select-window (get-buffer-window conversation))
          (mx-machina-focus id)
          (should (= (length (window-list)) 1))
          (mx-machina) ; Showing the overview also exits focus.
          (should (= (length (window-list)) 3))
          (should (get-buffer-window conversation)))))))

(ert-deftest mx-machina-focus-failure-leaves-layout-intact ()
  (mx-machina-test-with-store
    (mx-machina-create "Test" repo "test")
    (mx-machina)
    (let ((before (current-window-configuration)))
      (cl-letf (((symbol-function 'mx-machina-start)
                 (lambda (_id) (user-error "Cannot resume"))))
        (should-error (mx-machina-focus "test") :type 'user-error))
      (should (compare-window-configurations before (current-window-configuration)))
      (should-not (frame-parameter nil 'mx-machina-focus-layout)))))

(ert-deftest mx-machina-sidebar-coexists-with-another-side-window ()
  (mx-machina-test-with-store
    (let ((buffer (generate-new-buffer "*Other sidebar test*")))
      (unwind-protect
          (let ((other (display-buffer buffer '((display-buffer-in-side-window)
                                                (side . left) (slot . 0)))))
            (mx-machina-create "Test" repo "test")
            (mx-machina)
            (should (window-live-p other))
            (should (eq (window-buffer other) buffer))
            (should-not (eq other (selected-window))))
        (kill-buffer buffer)))))

(ert-deftest mx-machina-close-view-restores-editor-without-killing-drafts ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Test" repo "test"))
           (first (generate-new-buffer "*View first*"))
           (second (generate-new-buffer "*View second*")))
      (dolist (buffer (list first second))
        (with-current-buffer buffer
          (setq-local mx-machina--managed-id id)
          (insert "unsent draft")))
      (split-window-right)
      (mx-machina)
      (let ((before (current-window-configuration)))
        (mx-machina--show-conversation first)
        (should (= (length (window-list)) 2))
        (mx-machina--show-conversation second)
        (cl-letf (((symbol-function 'mx-machina-start) (lambda (_id) second)))
          (mx-machina-focus id))
        (should (= (length (window-list)) 1))
        (mx-machina-close-view)
        (should (compare-window-configurations before (current-window-configuration)))
        (should-not (frame-parameter nil 'mx-machina-conversation-layout))
        (should-not (frame-parameter nil 'mx-machina-focus-layout))
        (dolist (buffer (list first second))
          (should (buffer-live-p buffer))
          (should-not (get-buffer-window buffer))
          (should (equal (with-current-buffer buffer (buffer-string)) "unsent draft"))))
      ;; Reopening must capture the new editing layout rather than an old one.
      (mx-machina--select-main-window)
      (delete-other-windows)
      (mx-machina--show-conversation first)
      (mx-machina-close-view)
      (should (= (length (window-list)) 2)))))

(ert-deftest mx-machina-sidebar-labels-state-and-directory-per-session ()
  (mx-machina-test-with-store
    (let* ((other (expand-file-name "other-worktree" temporary))
           (first (mx-machina-create "First" repo "test")))
      (mx-machina--git repo "worktree" "add" "-b" "other" other)
      (let* ((second (mx-machina-create "Second" other "test"))
             (run (mx-machina--begin-run second)))
        (mx-machina--observe second run "live" "approval" "saved")
        (mx-machina)
        (should (equal (mx-machina--sidebar-id) first))
        (should (string-match-p (regexp-quote "● First\n") (buffer-string)))
        (should (string-match-p (regexp-quote "● Second\n") (buffer-string)))
        (should-not (string-match-p "Dir:" (buffer-string)))
        (should (= (count-lines (point-min) (point-max)) 2))
        (mx-machina-sidebar-next)
        (mx-machina-sidebar-expand)
        (should (string-match-p (regexp-quote "[APPROVAL]") (buffer-string)))
        (should (string-match-p (regexp-quote (abbreviate-file-name (file-truename other))) (buffer-string)))
        (should truncate-lines)))))

(ert-deftest mx-machina-sidebar-active-marker-follows-view-not-navigation ()
  (mx-machina-test-with-store
    (let* ((first (mx-machina-create "First" repo "test"))
           (second (mx-machina-create "Second" repo "test"))
           (buffer (get-buffer-create "*Active agent test*")))
      (with-current-buffer buffer (setq-local mx-machina--managed-id first))
      (mx-machina--show-conversation buffer)
      (with-current-buffer "*M-x Machina Sidebar*"
        (should (equal mx-machina--active-session first))
        (goto-char (point-min))
        (search-forward "First")
        (should (memq 'mx-machina-active-session (get-text-property (1- (point)) 'face)))
        (should-not (string-match-p "▶" (buffer-string)))
        (goto-char (mx-machina--sidebar-position second))
        (mx-machina--update-active-session)
        (should (equal (mx-machina--sidebar-id) second))
        (should (equal mx-machina--active-session first)))
      (mx-machina-close-view)
      (should-not mx-machina--active-session)
      (with-current-buffer "*M-x Machina Sidebar*"
        (goto-char (point-min))
        (search-forward "First")
        (should-not (memq 'mx-machina-active-session
                          (ensure-list (get-text-property (1- (point)) 'face))))))))

(ert-deftest mx-machina-v1-migration-preserves-live-identity ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Existing" repo "test"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "live" "working" "original-conversation")
      ;; Reconstruct a v1 registry, including an in-flight run.
      (dolist (column '("folder" "unread" "model" "project" "archived"))
        (mx-machina--exec (concat "ALTER TABLE sessions DROP COLUMN " column)))
      (mx-machina--exec "DROP TABLE folders")
      (mx-machina--exec "PRAGMA user_version=1")
      (mx-machina-store-migrate)
      (mx-machina-store-migrate)
      (let ((session (mx-machina-session id)))
        (should (equal (mx-machina-session-conversation session) "original-conversation"))
        (should (equal (mx-machina-session-run session) run))
        (should (equal (mx-machina-session-status session) "live"))
        (should (equal (mx-machina-session-folder session) ""))
        (should-not (mx-machina-unread-p session)))
      (should (= 3 (caar (mx-machina--query "PRAGMA user_version")))))))

(ert-deftest mx-machina-folders-names-unread-and-model-survive-reopen ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Harness" repo "test" "Work/Wix Panels"))
           (conversation "keep-me"))
      (mx-machina--exec "UPDATE sessions SET conversation=?,unread=1,model=? WHERE id=?"
                          conversation "Reported model" id)
      (mx-machina-new-folder "Personal/Experiments/Empty")
      (mx-machina-move id "Work/Wix Panels/Deep/More/Even More")
      (mx-machina-rename id "Migrating to Effect v4")
      (should-error (mx-machina-folder-create "Work/../Oops") :type 'user-error)
      (mx-machina-store-close)
      (let ((session (mx-machina-session id)))
        (should (equal (mx-machina-session-folder session) "Work/Wix Panels/Deep/More/Even More"))
        (should (equal (mx-machina-session-name session) "Migrating to Effect v4"))
        (should (equal (mx-machina-session-conversation session) conversation))
        (should (equal (mx-machina-session-model session) "Reported model"))
        (should (equal (mx-machina-session-directory session) (file-truename repo)))
        (should (mx-machina-unread-p session)))
      (should (member "Personal/Experiments/Empty" (mx-machina-folders)))
      (should (member "Work/Wix Panels/Deep/More" (mx-machina-folders))))))

(ert-deftest mx-machina-folders-collapse-with-attention-counts ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Harness" repo "test" "Work/Wix Panels"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "live" "working" "saved")
      (mx-machina--exec "UPDATE sessions SET unread=1 WHERE id=?" id)
      (mx-machina)
      (should (equal (mx-machina--sidebar-node) "folder:Work"))
      (should (string-match-p "Harness" (buffer-string)))
      (mx-machina-sidebar-open)
      (should-not (string-match-p "Harness" (buffer-string)))
      (should (string-match-p "1 working" (buffer-string)))
      (should (string-match-p "1 NEW" (buffer-string)))
      (should (equal (mx-machina--sidebar-node) "folder:Work"))
      (mx-machina-refresh)
      (should (equal (mx-machina--sidebar-node) "folder:Work"))
      (mx-machina-sidebar-open)
      (mx-machina-sidebar-next)
      (should (equal (mx-machina--sidebar-node) "folder:Work/Wix Panels"))
      (mx-machina-sidebar-next)
      (should (equal (mx-machina--read-id) id))
      (should (zerop (hash-table-count mx-machina--running))))))

(ert-deftest mx-machina-unread-respects-viewing-and-stale-transports ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Unread" repo "test"))
           (run (mx-machina--begin-run id))
           (buffer (generate-new-buffer "*Unread test*"))
           (transport (mx-machina--transport-create :buffer buffer)))
      (with-current-buffer buffer (setq-local mx-machina--managed-id id))
      (unwind-protect
          (progn
            (puthash id (cons run transport) mx-machina--running)
            (mx-machina--observe id run "live" "input" "saved")
            (mx-machina--backend-notice transport 'message nil)
            (should (mx-machina-unread-p (mx-machina-session id)))
            (should-not (mx-machina--conversation-reading-p buffer))
            (mx-machina--maybe-read-current)
            (should (mx-machina-unread-p (mx-machina-session id)))
            (mx-machina--show-conversation buffer)
            (cl-letf (((symbol-function 'mx-machina--conversation-reading-p) (lambda (_) nil)))
              (mx-machina--maybe-read-current)
              (should (mx-machina-unread-p (mx-machina-session id))))
            (let ((mx-machina-read-delay 0))
              (cl-letf (((symbol-function 'mx-machina--conversation-reading-p) (lambda (_) t)))
                (mx-machina--maybe-read-current)
                (should-not (mx-machina-unread-p (mx-machina-session id)))))
            (mx-machina--observe id run "stopped" "unknown")
            (mx-machina--backend-notice transport 'message nil)
            (should-not (mx-machina-unread-p (mx-machina-session id))))
        (remhash id mx-machina--running)))))

(ert-deftest mx-machina-spinner-uses-cache-and-preserves-node ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Working" repo "test"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "live" "working" "saved")
      (mx-machina)
      (let ((before (buffer-string))
            (mx-machina-animate t))
        (cl-letf (((symbol-function 'mx-machina--query) (lambda (&rest _) (error "Animation queried SQLite"))))
          (mx-machina--ui-tick))
        (should-not (equal before (buffer-string)))
        (should (equal (mx-machina--sidebar-id) id))
        (save-excursion
          (goto-char (point-min))
          (search-forward "▸ ")
          (should (eq (get-text-property (point) 'face) 'mx-machina-working))))
      (mx-machina--observe id run "stopped" "unknown")
      (mx-machina-refresh)
      (should-not mx-machina--ui-timer))))

(ert-deftest mx-machina-read-delay-does-not-accumulate-between-visits ()
  (mx-machina-test-with-store
    (let* ((first (mx-machina-create "First" repo "test"))
           (second (mx-machina-create "Second" repo "test"))
           (first-buffer (generate-new-buffer "*Read first*"))
           (second-buffer (generate-new-buffer "*Read second*"))
           (mx-machina-read-delay 5)
           (now 100.0))
      (with-current-buffer first-buffer (setq-local mx-machina--managed-id first))
      (with-current-buffer second-buffer (setq-local mx-machina--managed-id second))
      (mx-machina--exec "UPDATE sessions SET unread=1")
      (mx-machina--show-conversation first-buffer)
      (cl-letf (((symbol-function 'float-time) (lambda (&rest _) now))
                ((symbol-function 'mx-machina--conversation-reading-p) (lambda (_) t)))
        (cl-labels ((advance (seconds)
                      (dotimes (_ (* seconds 4))
                        (setq now (+ now 0.25))
                        (mx-machina--maybe-read-current))))
          (run-hooks 'post-command-hook)
          (advance 4)
          (should (mx-machina-unread-p (mx-machina-session first)))
          ;; A brief visit to another agent must reset the first one's timer.
          (switch-to-buffer second-buffer)
          (run-hooks 'post-command-hook)
          (advance 1)
          (switch-to-buffer first-buffer)
          (run-hooks 'post-command-hook)
          (advance 4)
          (should (mx-machina-unread-p (mx-machina-session first)))
          (should (mx-machina-unread-p (mx-machina-session second)))
          (advance 1)
          (should-not (mx-machina-unread-p (mx-machina-session first)))
          (should (mx-machina-unread-p (mx-machina-session second)))
          ;; Explicit acknowledgment is immediate even while viewing another agent.
          (mx-machina-mark-read second)
          (should-not (mx-machina-unread-p (mx-machina-session second))))))))

(ert-deftest mx-machina-read-delay-resets-on-lost-visibility-output-and-sleep ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Read delay" repo "test"))
           (buffer (generate-new-buffer "*Read delay*"))
           (run (mx-machina--begin-run id))
           (transport (mx-machina--transport-create :buffer buffer))
           (mx-machina-read-delay 3)
           (visible t)
           (now 100.0))
      (with-current-buffer buffer (setq-local mx-machina--managed-id id))
      (unwind-protect
          (progn
            (puthash id (cons run transport) mx-machina--running)
            (mx-machina--observe id run "live" "input" "saved")
            (mx-machina--backend-notice transport 'message nil)
            (mx-machina--show-conversation buffer)
            (cl-letf (((symbol-function 'float-time) (lambda (&rest _) now))
                      ((symbol-function 'mx-machina--conversation-reading-p) (lambda (_) visible)))
              (cl-labels ((advance (seconds)
                            (dotimes (_ (* seconds 4))
                              (setq now (+ now 0.25))
                              (mx-machina--maybe-read-current))))
                (mx-machina--maybe-read-current)
                (advance 2)
                ;; Scrolling away or losing focus resets, even before a tick.
                (setq visible nil)
                (mx-machina--read-view-changed)
                (setq visible t)
                (mx-machina--read-view-changed)
                (advance 2)
                (should (mx-machina-unread-p (mx-machina-session id)))
                ;; New output gets a full reading interval, even if already unread.
                (mx-machina--backend-notice transport 'message nil)
                (mx-machina--maybe-read-current)
                (advance 2)
                (should (mx-machina-unread-p (mx-machina-session id)))
                ;; An unobserved system-sleep/event-loop gap does not count.
                (setq now (+ now 60))
                (mx-machina--maybe-read-current)
                (should (mx-machina-unread-p (mx-machina-session id)))
                (advance 2)
                (should (mx-machina-unread-p (mx-machina-session id)))
                (advance 1)
                (should-not (mx-machina-unread-p (mx-machina-session id)))
                (should-not mx-machina--read-dwell))))
        (remhash id mx-machina--running)))))

(ert-deftest mx-machina-lock-survives-disabled-editor-lockfiles ()
  (mx-machina-test-with-store
    (let* ((create-lockfiles nil)
           (id (mx-machina-create "Owner" repo "test"))
           (run (mx-machina--begin-run id))
           (file mx-machina--db-file))
      (mx-machina--observe id run "live" "working" "saved")
      (should (eq (file-locked-p file) t))
      (with-temp-buffer
        (should (= 0 (call-process
                      (expand-file-name invocation-name invocation-directory) nil t nil
                      "--batch" "-Q" "-L" (file-name-directory (locate-library "mx-machina-store"))
                      "--eval" (prin1-to-string
                                `(progn (require 'mx-machina-store)
                                        (setq create-lockfiles nil mx-machina-directory ,mx-machina-directory)
                                        (condition-case nil
                                            (progn (mx-machina-store-open) (princ "OPENED"))
                                          (user-error (princ "BLOCKED"))))))))
        (should (equal (buffer-string) "BLOCKED")))
      (should (equal (mx-machina-session-status (mx-machina-session id)) "live"))
      (mx-machina-store-close)
      (should-not (file-locked-p file)))))

(ert-deftest mx-machina-folder-order-groups-prefix-siblings ()
  (mx-machina-test-with-store
    (dolist (folder '("Work Panels" "Work/Harness/Child" "Work/Harness-other" "Work-other"))
      (mx-machina-folder-create folder))
    (should (equal (mx-machina-folders)
                   '("Work" "Work/Harness" "Work/Harness/Child" "Work/Harness-other" "Work Panels" "Work-other")))
    (mx-machina)
    (should (string-match-p "Work (0)\n  ▾ Harness (0)\n    ▾ Child (0)" (buffer-string)))))

(ert-deftest mx-machina-empty-model-notice-preserves-known-model ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Model" repo "test"))
           (run (mx-machina--begin-run id))
           (transport (mx-machina--transport-create)))
      (mx-machina--observe id run "live" "input" "saved")
      (puthash id (cons run transport) mx-machina--running)
      (unwind-protect
          (progn
            (mx-machina--backend-notice transport 'metadata '(:model "Known"))
            (dolist (model '(nil ""))
              (mx-machina--backend-notice transport 'metadata (list :model model))
              (should (equal (mx-machina-session-model (mx-machina-session id)) "Known")))
            (cl-letf (((symbol-function 'mx-machina-sessions)
                       (lambda () (ert-fail "Single-session lookup scanned the registry"))))
              (should (equal (mx-machina-session-name (mx-machina-session id)) "Model"))))
        (remhash id mx-machina--running)))))

(ert-deftest mx-machina-sidebar-observers-and-compact-identity ()
  (mx-machina-test-with-store
    (should-not (memq #'mx-machina--update-active-session window-buffer-change-functions))
    (let* ((id (mx-machina-create "Migrating to Effect v4" repo "test" "A/B/C/D/E/F/G"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "live" "working" "saved")
      (mx-machina--exec "UPDATE sessions SET unread=1 WHERE id=?" id)
      (mx-machina)
      (should (memq #'mx-machina--update-active-session window-buffer-change-functions))
      (goto-char (mx-machina--sidebar-position id))
      (let ((start (point)))
        (search-forward "Migrating")
        (should (<= (- (point) start (length "Migrating")) 14))
        (should (string-match-p "Migrating to Effect v4" (get-text-property start 'help-echo))))
      (cl-letf (((symbol-function 'mx-machina--query)
                 (lambda (&rest _) (ert-fail "TAB queried the registry"))))
        (mx-machina-sidebar-expand))
      (kill-buffer (current-buffer))
      (should-not (memq #'mx-machina--update-active-session window-buffer-change-functions))
      (mx-machina)
      (mx-machina-shutdown)
      (should-not (memq #'mx-machina--update-active-session window-selection-change-functions)))))

(ert-deftest mx-machina-animation-skips-hidden-conversation-headers ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Hidden" repo "test"))
           (buffer (get-buffer-create "*Header test*")))
      (with-current-buffer buffer
        (setq-local mx-machina--managed-id id)
        (mx-machina-conversation-mode 1)
        (setq mx-machina--identity "unchanged"))
      (cl-letf (((symbol-function 'buffer-list)
                 (lambda (&rest _) (ert-fail "Animation scanned all buffers"))))
        (mx-machina--refresh-headers t))
      (should (equal (buffer-local-value 'mx-machina--identity buffer) "unchanged"))
      (kill-buffer buffer)
      (should-not (memq buffer mx-machina--conversation-buffers)))))

(ert-deftest mx-machina-transaction-rolls-back-nonlocal-exits-and-failed-commit ()
  (mx-machina-test-with-store
    (mx-machina-store-open)
    (mx-machina--exec "CREATE TABLE transaction_probe (value TEXT)")
    (dolist (exit '(error quit throw commit-error commit-nil))
      (let ((commit (symbol-function 'sqlite-commit)))
        (cl-letf (((symbol-function 'sqlite-commit)
                   (lambda (db)
                     (pcase exit
                       ('commit-error (error "Fixture commit failure"))
                       ('commit-nil nil)
                       (_ (funcall commit db))))))
          (condition-case nil
              (catch 'abort
                (mx-machina--with-transaction mx-machina--db
                  (mx-machina--exec "INSERT INTO transaction_probe VALUES ('rollback')")
                  (pcase exit
                    ('error (error "Fixture body failure"))
                    ('quit (signal 'quit nil))
                    ('throw (throw 'abort nil)))))
            ((error quit) nil))))
      (should-not (mx-machina--query "SELECT * FROM transaction_probe")))
    (let ((evaluations 0))
      (should-not
       (mx-machina--with-transaction (progn (cl-incf evaluations) mx-machina--db)
         (mx-machina--exec "INSERT INTO transaction_probe VALUES ('committed')")
         nil))
      (should (= evaluations 1)))
    (should (equal '(("committed")) (mx-machina--query "SELECT * FROM transaction_probe")))))
