;;; mx-machina-diagnostics-tests.el --- Local diagnosis tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(unless (boundp 'mx-machina-test-root)
  (load (expand-file-name "mx-machina-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))
(require 'mx-machina-diagnostics)

(defun mx-machina-test-diagnostic-check (id label)
  "Return the diagnostic row for ID with LABEL."
  (assoc label (plist-get (mx-machina-diagnostics--collect id) :checks)))

(ert-deftest mx-machina-diagnostics-launch-blockers ()
  (mx-machina-test-with-store
    (let ((id (mx-machina-create "Broken profile" repo "test"))
          configs)
      (cl-letf (((symbol-function 'mx-machina-backend-configs) (lambda () configs))
                ((symbol-function 'mx-machina-backend-start) (lambda (&rest _) (ert-fail "Diagnostics launched an agent"))))
        (should (equal (cdr (mx-machina-test-diagnostic-check id "Profile"))
                       '(blocked "test — unavailable; restore this profile in your configuration")))
        (setq configs '(((:identifier . test) (:interface . eat) (:command . ("no-such-agent-executable-92841")))))
        (should (eq (cadr (mx-machina-test-diagnostic-check id "Executable")) 'blocked))
        (cl-letf (((symbol-function 'locate-library) (lambda (&rest _) nil))
                  ((symbol-function 'featurep) (lambda (&rest _) nil)))
          (should (eq (cadr (mx-machina-test-diagnostic-check id "Dependency: eat")) 'blocked))))
      (cl-letf (((symbol-function 'mx-machina-backend-configs) (lambda () (error "bad configuration SECRET"))))
        (let ((report (mx-machina-diagnostics--text (mx-machina-diagnostics--collect id))))
          (should (string-match-p "Configuration inspection failed" report))
          (should-not (string-match-p "SECRET" report)))))))

(ert-deftest mx-machina-diagnostics-worktree-missing-and-mismatch ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Checkout" repo "test"))
           (before (mx-machina--query "SELECT * FROM sessions")))
      (cl-letf (((symbol-function 'mx-machina-backend-configs) #'ignore))
        (mx-machina--git repo "checkout" "-b" "changed")
        (should (equal (cdr (mx-machina-test-diagnostic-check id "Actual branch")) '(blocked "changed")))
        (should (eq (cadr (mx-machina-test-diagnostic-check id "Worktree mismatch")) 'blocked))
        (rename-file repo (expand-file-name "relocated" temporary))
        (should (string-match-p "Directory missing" (nth 2 (mx-machina-test-diagnostic-check id "Worktree"))))
        (should (equal before (mx-machina--query "SELECT * FROM sessions")))))))

(ert-deftest mx-machina-diagnostics-cold-registry-does-not-reconcile ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Saved live agent" repo "test"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "live" "working" "durable-id")
      (mx-machina--exec "UPDATE sessions SET unread=1 WHERE id=?" id)
      (let ((sessions (mx-machina--query "SELECT * FROM sessions"))
            (runs (mx-machina--query "SELECT * FROM runs")))
        (mx-machina-store-close)
        (cl-letf (((symbol-function 'mx-machina-backend-configs) #'ignore)
                  ((symbol-function 'mx-machina-store-open) (lambda () (ert-fail "Diagnostics opened the manager"))))
          (should (eq (cadr (mx-machina-test-diagnostic-check id "Observation")) 'warning))
          (should (equal (nth 2 (mx-machina-test-diagnostic-check id "Conversation")) "durable-id"))
          (should-not mx-machina--db)
          (let ((db (sqlite-open (expand-file-name "sessions.sqlite" mx-machina-directory))))
            (unwind-protect
                (progn
                  (should (equal sessions (sqlite-select db "SELECT * FROM sessions")))
                  (should (equal runs (sqlite-select db "SELECT * FROM runs"))))
              (sqlite-close db))))))))

(ert-deftest mx-machina-diagnostics-no-registry-or-migration ()
  (mx-machina-test-with-store
    (should-error (mx-machina-diagnostics--sessions) :type 'user-error)
    (should-not (file-exists-p mx-machina-directory))
    (mx-machina-create "Old schema" repo "test")
    (mx-machina--exec "PRAGMA user_version=2")
    (should-error (mx-machina-diagnostics--sessions) :type 'user-error)
    (should (= 2 (caar (mx-machina--query "PRAGMA user_version"))))))

(ert-deftest mx-machina-diagnostics-process-and-bridge-without-polling ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Terminal" repo "test"))
           (run (mx-machina--begin-run id))
           (buffer (generate-new-buffer "*Diagnostic fixture terminal*"))
           (process (make-pipe-process :name "diagnostic-fixture" :buffer buffer :noquery t))
           (transport (mx-machina--transport-create :buffer buffer))
           (timer (run-at-time 3600 nil #'ignore))
           (file (expand-file-name "events.jsonl" temporary)))
      (unwind-protect
          (progn
            (write-region "" nil file nil 'silent)
            (puthash id (cons run transport) mx-machina--running)
            (with-current-buffer buffer
              (setq-local mx-machina--backend-kind 'eat
                          mx-machina-claude--started-at (- (float-time) 30)
                          mx-machina-claude--timer timer
                          mx-machina-claude--event-file file
                          mx-machina-claude--offset 17))
            (cl-letf (((symbol-function 'mx-machina-backend-configs)
                       (lambda () '(((:identifier . test) (:interface . eat) (:command . ("python3"))))))
                      ((symbol-function 'mx-machina-claude--poll)
                       (lambda (&rest _) (ert-fail "Diagnostics consumed hook events"))))
              (should (eq (cadr (mx-machina-test-diagnostic-check id "Process now")) 'ok))
              (should (eq (cadr (mx-machina-test-diagnostic-check id "SessionStart")) 'blocked))
              (setf (mx-machina-transport-ready transport) t)
              (should (eq (cadr (mx-machina-test-diagnostic-check id "SessionStart")) 'ok))
              (should (eq (cadr (mx-machina-test-diagnostic-check id "Event poller")) 'ok))
              (should (equal (nth 2 (mx-machina-test-diagnostic-check id "Event file")) "Readable; 17 bytes consumed"))
              (cancel-timer timer)
              (should (eq (cadr (mx-machina-test-diagnostic-check id "Event poller")) 'warning))
              (delete-file file)
              (should (eq (cadr (mx-machina-test-diagnostic-check id "Event file")) 'warning))
              (delete-process process)
              (remhash id mx-machina--running)
              (mx-machina--observe id run "exited" "unknown" "durable-id")
              (should (string-match-p "Exited" (nth 2 (mx-machina-test-diagnostic-check id "Process now"))))
              (should (string-match-p "Inactive" (nth 2 (mx-machina-test-diagnostic-check id "Status bridge"))))))
        (remhash id mx-machina--running)
        (cancel-timer timer)
        (when (process-live-p process) (delete-process process))
        (kill-buffer buffer)))))

(ert-deftest mx-machina-diagnostics-ui-copy-return-preserves-agent ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Inspect me" repo "test" "Work/Project"))
           (run (mx-machina--begin-run id))
           (source (generate-new-buffer "*Diagnostic source draft*"))
           (kill-ring nil))
      (unwind-protect
          (progn
            (mx-machina--observe id run "failed" "unknown" "durable-id" "Authentication failed: SECRET-ERROR private prompt")
            (mx-machina--exec "UPDATE sessions SET unread=1 WHERE id=?" id)
            (switch-to-buffer source)
            (insert "Unsent draft")
            (mx-machina)
            (let ((before (mx-machina--query "SELECT * FROM sessions"))
                  (runs (mx-machina--query "SELECT * FROM runs"))
                  (windows (length (window-list))))
              (cl-letf (((symbol-function 'mx-machina-backend-configs)
                         (lambda () '(((:identifier . test) (:interface . eat)
                                       (:command . ("python3" "--key=SECRET-ARGV"))
                                       (:environment . ("TOKEN=SECRET-ENV")))))))
                ;; Follow the same command used by i, including the interactive picker.
                (cl-letf (((symbol-function 'mx-machina-diagnostics--read-id) (lambda () id)))
                  (call-interactively #'mx-machina-details))
                (should (= windows (length (window-list))))
                (should (eq major-mode 'mx-machina-diagnostics-mode))
                (when (bound-and-true-p evil-mode) (evil-normal-state))
                (should buffer-read-only)
                (should-not mx-machina--managed-id)
                (should (string-match-p "SECRET-ERROR" (buffer-string)))
                (should (eq (key-binding (kbd "g")) #'mx-machina-diagnostics-refresh))
                (call-interactively (key-binding (kbd "g")))
                (should (eq (key-binding (kbd "w")) #'mx-machina-diagnostics-copy))
                (call-interactively (key-binding (kbd "w")))
                (should (string-match-p "Authentication-related failure" (car kill-ring)))
                (should (string-match-p "durable-id" (car kill-ring)))
                (should-not (string-match-p "SECRET-\\|private prompt\\|--key=" (car kill-ring)))
                (should (equal before (mx-machina--query "SELECT * FROM sessions")))
                (should (equal runs (mx-machina--query "SELECT * FROM runs")))
                (should (zerop (hash-table-count mx-machina--running)))
                (should (eq (key-binding (kbd "q")) #'mx-machina-diagnostics-return))
                (call-interactively (key-binding (kbd "q")))
                (should (eq (current-buffer) source))
                (should (equal (buffer-string) "Unsent draft")))))
        (with-current-buffer source (set-buffer-modified-p nil))
        (kill-buffer source)))))

(ert-deftest mx-machina-diagnostics-acp-does-not-invoke-client-factory ()
  (mx-machina-test-with-store
    (let ((id (mx-machina-create "ACP" repo "test")))
      (mx-machina-archive id)
      (cl-letf (((symbol-function 'mx-machina-backend-configs)
                 (lambda () (list (list '(:identifier . test) '(:interface . agent-shell)
                                       (cons :client-maker (lambda (&rest _) (ert-fail "Created an ACP client"))))))))
        (should (eq (cadr (mx-machina-test-diagnostic-check id "Executable")) 'warning))
        (should (string-match-p "ACP events" (nth 2 (mx-machina-test-diagnostic-check id "Status bridge"))))
        (should (eq (cadr (mx-machina-test-diagnostic-check id "Archive")) 'blocked))
        (should (string-match-p "Not created yet" (nth 2 (mx-machina-test-diagnostic-check id "Conversation"))))))))

;;; mx-machina-diagnostics-tests.el ends here
