;;; mx-machina-board-tests.el --- Board navigation and state tests -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
(unless (boundp 'mx-machina-test-root)
  (load (expand-file-name "mx-machina-tests.el" (file-name-directory (or load-file-name buffer-file-name))) nil t))
(require 'mx-machina-board)

(ert-deftest mx-machina-board-renders-all-states-without-side-effects ()
  (mx-machina-test-with-store
    (let (ids)
      (dolist (state '("working" "approval" "waiting" "input" "unknown"))
        (let* ((id (mx-machina-create (concat "Agent " state) repo "test" "Work/Panels"))
               (run (mx-machina--begin-run id)))
          (push id ids)
          (mx-machina--observe id run "live" state "saved")))
      (push (mx-machina-create "Stopped" repo "test" "Work/Panels") ids)
      (mx-machina--exec "UPDATE sessions SET unread=1")
      (let ((before (mx-machina--query "SELECT * FROM sessions")))
        (cl-letf (((symbol-function 'mx-machina-start) (lambda (&rest _) (ert-fail "Board launched an agent"))))
          (mx-machina-board)
          (dolist (width '(22 56 112))
            (mx-machina-board--render width)
            (should (= (length ids) (length mx-machina-board--positions)))
            (should (string-match-p "Waiting  2" (buffer-string)))
            (should (string-match-p "Other  1" (buffer-string)))
            (should (string-match-p "NEW" (buffer-string)))
            (should-not mx-machina--managed-id)
            (mx-machina-board-next)
            (mx-machina--maybe-read-current)
            (should (equal before (mx-machina--query "SELECT * FROM sessions")))
            (dolist (line (split-string (buffer-string) "\n"))
              (should (<= (string-width line) width)))))))))

(ert-deftest mx-machina-board-wraps-names-and-keeps-selection-across-status ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Migrating to Effect v4 and reviewing the Harness" repo "test" "Work/Panels/Deep/Nesting"))
           (run (mx-machina--begin-run id)))
      (mx-machina--observe id run "live" "working" "saved")
      (mx-machina-board)
      (mx-machina-board--render 28)
      (should (string-match-p "Harness" (buffer-string)))
      (should (equal id mx-machina-board--selection))
      (mx-machina--observe id run "live" "approval")
      (mx-machina-refresh)
      (should (equal id mx-machina-board--selection))
      (should (equal id (get-text-property (point) 'mx-machina-id)))
      (should (equal (mx-machina--read-id) id))
      (cl-letf (((symbol-function 'mx-machina--query) (lambda (&rest _) (ert-fail "Reflow queried the registry"))))
        (mx-machina-board--render 110))
      (should (equal id mx-machina-board--selection)))))

(ert-deftest mx-machina-board-folder-scope-respects-boundaries-and-archive ()
  (mx-machina-test-with-store
    (let ((first (mx-machina-create "Inside" repo "test" "Work"))
          (deep (mx-machina-create "Deep" repo "test" "Work/Panels/Harness"))
          (sibling (mx-machina-create "Sibling" repo "test" "Work Panels"))
          (archived (mx-machina-create "Archived" repo "test" "Work")))
      (mx-machina-archive archived)
      (mx-machina-folder-create "Empty")
      (mx-machina-board)
      (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Folder: Work")))
        (mx-machina-board-scope))
      (should (assoc first mx-machina-board--positions))
      (should (assoc deep mx-machina-board--positions))
      (should-not (assoc sibling mx-machina-board--positions))
      (should-not (assoc archived mx-machina-board--positions))
      (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Folder: Empty")))
        (mx-machina-board-scope))
      (should-not mx-machina-board--positions)
      (should (string-match-p "No agents in this scope" (buffer-string)))
      (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "All folders")))
        (mx-machina-board-scope))
      (should (= 3 (length mx-machina-board--positions))))))

(ert-deftest mx-machina-board-ui-open-close-restores-card-and-draft ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Open me" repo "test"))
           (source (generate-new-buffer "*Board source*"))
           (conversation (generate-new-buffer "*Board conversation*")))
      (unwind-protect
          (progn
            (switch-to-buffer source)
            (insert "Editor draft")
            (with-current-buffer conversation
              (setq-local mx-machina--managed-id id)
              (insert "Agent draft"))
            (mx-machina-board)
            (when (bound-and-true-p evil-mode) (evil-motion-state))
            (should (eq (key-binding (kbd "RET")) #'mx-machina-board-open))
            (should (eq (key-binding (kbd "j")) #'mx-machina-board-down))
            (should (eq (key-binding (kbd "f")) #'mx-machina-board-scope))
            (let ((windows (length (window-list))))
              (cl-letf (((symbol-function 'mx-machina-start)
                         (lambda (selected) (should (equal id selected)) conversation)))
                (call-interactively (key-binding (kbd "RET"))))
              (should (eq (current-buffer) conversation))
              (should (= windows (length (window-list))))
              (mx-machina-close-view)
              (should (get-buffer-window "*M-x Machina Board*"))
              (with-current-buffer "*M-x Machina Board*"
                (should (equal id mx-machina-board--selection)))
              (mx-machina--select-main-window)
              (should (equal "Agent draft" (with-current-buffer conversation (buffer-string))))
              (should (eq (key-binding (kbd "q")) #'mx-machina-board-return))
              (call-interactively (key-binding (kbd "q")))
              (should (eq (current-buffer) source))
              (should (equal (buffer-string) "Editor draft"))))
        (dolist (buffer (list source conversation))
          (with-current-buffer buffer (set-buffer-modified-p nil)) (kill-buffer buffer))))))

(ert-deftest mx-machina-board-navigation-and-failed-open-preserve-view ()
  (mx-machina-test-with-store
    (let* ((first (mx-machina-create "First" repo "test"))
           (second (mx-machina-create "Second" repo "test"))
           (run (mx-machina--begin-run first)))
      (mx-machina--observe first run "live" "working" "saved")
      (mx-machina-board)
      (mx-machina-board--render 112)
      (should (equal first mx-machina-board--selection))
      (mx-machina-board-right)
      (should (equal second mx-machina-board--selection))
      (mx-machina-board-left)
      (should (equal first mx-machina-board--selection))
      (let ((layout (current-window-configuration)) (point (point)))
        (cl-letf (((symbol-function 'mx-machina-start) (lambda (&rest _) (user-error "Missing backend"))))
          (should-error (mx-machina-board-open) :type 'user-error))
        (should (= point (point)))
        (should (compare-window-configurations layout (current-window-configuration)))))))

(ert-deftest mx-machina-board-return-preserves-existing-conversation-close-layout ()
  (mx-machina-test-with-store
    (let* ((id (mx-machina-create "Existing" repo "test"))
           (source (generate-new-buffer "*Board editor layout*"))
           (conversation (generate-new-buffer "*Board existing conversation*")))
      (unwind-protect
          (progn
            (switch-to-buffer source)
            (with-current-buffer conversation (setq-local mx-machina--managed-id id))
            (mx-machina--show-conversation conversation)
            (let ((original (frame-parameter nil 'mx-machina-conversation-layout)))
              (mx-machina-board)
              (cl-letf (((symbol-function 'mx-machina-start) (lambda (&rest _) conversation)))
                (mx-machina-board-open))
              (mx-machina-close-view)
              (mx-machina--select-main-window)
              (mx-machina-board-return)
              (should (eq (current-buffer) conversation))
              (should (eq original (frame-parameter nil 'mx-machina-conversation-layout)))
              (mx-machina-close-view)
              (should (get-buffer-window source))))
        (kill-buffer source) (kill-buffer conversation)))))

;;; mx-machina-board-tests.el ends here
