;;; probe.el --- Checks after a real interactive startup -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later
;; Invoked by scripts/check-install, after Emacs has loaded the generated init.
(require 'cl-lib)
(require 'json)

(condition-case err
    (let* ((root (getenv "MXM_INSTALL_ROOT"))
           (kind (getenv "MXM_INSTALL_KIND"))
           (result (getenv "MXM_INSTALL_RESULT"))
           (identity-file (expand-file-name "agent-id" root)))
      (cl-assert (and root result (file-directory-p root)))
      (cl-assert (not noninteractive))
      (cl-assert after-init-time)
      (cl-assert (not init-file-had-error))
      (cl-assert (file-in-directory-p user-init-file root))
      (cl-assert (featurep 'mx-machina))
      (cl-assert (file-in-directory-p (symbol-file 'mx-machina) root))
      (cl-assert (sqlite-available-p))
      (cl-assert (file-in-directory-p mx-machina-directory root))
      (if (equal kind "doom")
          (progn
            (cl-assert (featurep 'doom))
            (cl-assert doom-init-time)
            (cl-assert (file-in-directory-p doom-user-dir root))
            (cl-assert (file-in-directory-p doom-local-dir root))
            (cl-assert (bound-and-true-p evil-mode))
            (cl-assert (eq (lookup-key doom-leader-map (kbd "o a a")) #'mx-machina)))
        (cl-assert (not (featurep 'doom))))
      (if (equal kind "plain")
          (dolist (entry '((eat mx-machina-eat-start "Install EAT")
                           (vterm mx-machina-vterm-start "Install vterm")))
            (cl-assert (not (locate-library (symbol-name (car entry)))))
            (let ((failure
                   (condition-case failure
                       (progn (funcall (cadr entry) "missing" root nil #'ignore) nil)
                     (user-error (error-message-string failure)))))
              (cl-assert (and failure (string-match-p (caddr entry) failure)))))
        ;; Resolve installed dependencies, including vterm's native module.
        ;; No real provider is launched and no account is configured.
        (require 'agent-shell)
        (require 'eat)
        ;; Accept only this documented build prompt in the disposable install.
        (setq vterm-always-compile-module t)
        (require 'vterm)
        (require 'vterm-module)
        (dolist (library '("agent-shell" "acp" "shell-maker" "eat" "vterm"))
          (cl-assert (file-in-directory-p (locate-library library) root)))
        (cl-assert (file-directory-p eat-term-terminfo-directory))
        (cl-assert (directory-files-recursively eat-term-terminfo-directory "eat"))
        (cl-assert (fboundp 'eat-term-input-event))
        (cl-assert (fboundp 'agent-shell-start)))
      (mx-machina)
      (cl-assert (derived-mode-p 'mx-machina-sidebar-mode))
      (when (equal kind "doom")
        (cl-assert (eq evil-state 'motion))
        (cl-assert (eq (key-binding (kbd "RET")) #'mx-machina-sidebar-open))
        (cl-assert (eq (key-binding (kbd "j")) #'mx-machina-sidebar-next)))
      (if (file-exists-p identity-file)
          (let* ((id (string-trim (with-temp-buffer
                                   (insert-file-contents identity-file) (buffer-string))))
                 (session (mx-machina-session id)))
            (cl-assert (equal (mx-machina-session-name session) "Installation fixture"))
            (cl-assert (equal (mx-machina-session-folder session) "Test/Nested"))
            (cl-assert (equal (mx-machina-session-status session) "stopped")))
        (let ((id (mx-machina-create "Installation fixture"
                                     (expand-file-name "worktree" root)
                                     "unconfigured-fixture" "Test/Nested")))
          (write-region id nil identity-file nil 'silent)))
      (cl-assert (= (length (mx-machina-sessions)) 1))
      (mx-machina-board)
      (cl-assert (derived-mode-p 'mx-machina-board-mode))
      (mx-machina-dashboard)
      (with-current-buffer (window-buffer (selected-window))
        (cl-assert (derived-mode-p 'mx-machina-mode)))
      (cl-assert (zerop (hash-table-count mx-machina--running)))
      (mx-machina-shutdown)
      (with-temp-file result
        (insert (json-encode `((ok . t) (kind . ,kind) (emacs . ,emacs-version)
                              (interactive-startup . t) (agents . 1)))))
      (kill-emacs 0))
  (error
   (with-temp-file (getenv "MXM_INSTALL_RESULT")
     (insert (json-encode `((ok . :json-false) (error . ,(error-message-string err))))))
   (kill-emacs 1)))
